// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.AWSDynamodbTable
//         + raw API struct dynamotypes.TableDescription
// Run: go generate ./cmd/insideout-import/awsdiscover/...
//      (or: go run ./cmd/enrichgen)

package awsdiscover

import (
	dynamotypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// keySchemaByType pulls the attribute name out of the KeySchema slice
// matching the requested key-type discriminator (HASH or RANGE). Returns
// the empty string when no element matches — the override snippet leaves
// the destination field unset in that case (matches TF's "absent when
// no range key" steady state).
func keySchemaByType(ks []dynamotypes.KeySchemaElement, kt dynamotypes.KeyType) string {
	for _, k := range ks {
		if k.KeyType == kt && k.AttributeName != nil {
			return *k.AttributeName
		}
	}
	return ""
}

// billingModeOrDefault returns the BillingMode string from a non-nil
// summary; on a nil summary it falls back to PROVISIONED — the implied
// default for legacy tables created before on-demand existed. Keeps the
// drift comparator stable on tables that report no summary.
func billingModeOrDefault(b *dynamotypes.BillingModeSummary) string {
	if b == nil || b.BillingMode == "" {
		return string(dynamotypes.BillingModeProvisioned)
	}
	return string(b.BillingMode)
}

func mapDynamodbTable(b *dynamotypes.TableDescription, accountID string) *generated.AWSDynamodbTable {
	out := &generated.AWSDynamodbTable{}
	out.BillingMode = generated.LiteralOf(billingModeOrDefault(b.BillingModeSummary))
	if b.DeletionProtectionEnabled != nil {
		out.DeletionProtectionEnabled = generated.LiteralOf(*b.DeletionProtectionEnabled)
	}
	if n := keySchemaByType(b.KeySchema, dynamotypes.KeyTypeHash); n != "" {
		out.HashKey = generated.LiteralOf(n)
	}
	if b.TableName != nil && *b.TableName != "" {
		out.Name = generated.LiteralOf(*b.TableName)
	}
	if n := keySchemaByType(b.KeySchema, dynamotypes.KeyTypeRange); n != "" {
		out.RangeKey = generated.LiteralOf(n)
	}
	if billingModeOrDefault(b.BillingModeSummary) == string(dynamotypes.BillingModeProvisioned) && b.ProvisionedThroughput != nil && b.ProvisionedThroughput.ReadCapacityUnits != nil {
		out.ReadCapacity = generated.LiteralOf(float64(*b.ProvisionedThroughput.ReadCapacityUnits))
	}
	if b.StreamSpecification != nil && b.StreamSpecification.StreamEnabled != nil {
		out.StreamEnabled = generated.LiteralOf(*b.StreamSpecification.StreamEnabled)
	}
	if b.StreamSpecification != nil && b.StreamSpecification.StreamEnabled != nil && *b.StreamSpecification.StreamEnabled && b.StreamSpecification.StreamViewType != "" {
		out.StreamViewType = generated.LiteralOf(string(b.StreamSpecification.StreamViewType))
	}
	if b.TableClassSummary != nil && b.TableClassSummary.TableClass != "" {
		out.TableClass = generated.LiteralOf(string(b.TableClassSummary.TableClass))
	}
	if billingModeOrDefault(b.BillingModeSummary) == string(dynamotypes.BillingModeProvisioned) && b.ProvisionedThroughput != nil && b.ProvisionedThroughput.WriteCapacityUnits != nil {
		out.WriteCapacity = generated.LiteralOf(float64(*b.ProvisionedThroughput.WriteCapacityUnits))
	}
	if len(b.AttributeDefinitions) > 0 {
		blocks := make([]generated.AWSDynamodbTableAttribute, 0, len(b.AttributeDefinitions))
		for i := range b.AttributeDefinitions {
			blocks = append(blocks, enrichAWSDynamodbTableAttribute(&b.AttributeDefinitions[i]))
		}
		if len(blocks) > 0 {
			out.Attribute = blocks
		}
	}

	if b.SSEDescription != nil && (b.SSEDescription.Status == dynamotypes.SSEStatusEnabled || b.SSEDescription.Status == dynamotypes.SSEStatusEnabling) {
		out.ServerSideEncryption = []generated.AWSDynamodbTableServerSideEncryption{enrichAWSDynamodbTableServerSideEncryption(b.SSEDescription)}
	}

	return out
}

func enrichAWSDynamodbTableAttribute(b *dynamotypes.AttributeDefinition) generated.AWSDynamodbTableAttribute {
	out := generated.AWSDynamodbTableAttribute{}
	if b.AttributeName != nil && *b.AttributeName != "" {
		out.Name = generated.LiteralOf(*b.AttributeName)
	}
	if b.AttributeType != "" {
		out.Type_ = generated.LiteralOf(string(b.AttributeType))
	}
	return out
}

func enrichAWSDynamodbTableServerSideEncryption(b *dynamotypes.SSEDescription) generated.AWSDynamodbTableServerSideEncryption {
	out := generated.AWSDynamodbTableServerSideEncryption{}
	out.Enabled = generated.LiteralOf(b.Status == dynamotypes.SSEStatusEnabled || b.Status == dynamotypes.SSEStatusEnabling)
	if b.KMSMasterKeyArn != nil && *b.KMSMasterKeyArn != "" {
		out.KMSKeyARN = generated.LiteralOf(*b.KMSMasterKeyArn)
	}
	return out
}
