// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: fetcher helpers for AWSDynamodbTable
// Run: go generate ./cmd/insideout-import/awsdiscover/...
//      (or: go run ./cmd/enrichgen)

package awsdiscover

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	dynamotypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// defaultDynamoDBTableFetchTags is the production tags fetch path.
// Returns the raw tag slice; the caller flattens it into the typed map.
// Pagination is not handled today — DynamoDB's tag-set is capped at 50 per
// table by the service, well below the per-page limit, so a single call
// covers every realistic case.
func defaultDynamoDBTableFetchTags(ctx context.Context, c *dynamodb.Client, tableArn string) ([]dynamotypes.Tag, error) {
	input := &dynamodb.ListTagsOfResourceInput{
		ResourceArn: aws.String(tableArn),
	}
	out, err := c.ListTagsOfResource(ctx, input)
	if err != nil {
		return nil, err
	}
	if out == nil {
		return nil, nil
	}
	return out.Tags, nil
}
