// Code generated by cmd/imported-codegen; DO NOT EDIT.
// @generated
//
// TS projection of the Layer-2 field policy map for the
// `aws_sqs_queue` Terraform resource. Mirrors
// pkg/composer/imported/policy/aws_sqs_queue.policy.go in
// luthersystems/insideout-terraform-presets — the Go side is the source
// of truth; this file is regenerated by
// `imported-codegen policy-ts --out <dir>`.
//
// Consumers see a pure-data POLICY array (one row per curated
// attribute, in stable Path order) plus the two projection helpers
// VisibleFieldsFor / EditableFieldsFor as `visibleFields(attrs)` /
// `editableFields(attrs)`. No runtime dependency on presets — only the
// shared axis-enum types from `./_policy`.

import type {
  FieldRow,
  FieldRole,
  FieldPillar,
  VisibilityPolicy,
  EditPolicy,
  SensitivityPolicy,
  ChangeRiskPolicy,
} from "./_policy";
import { projectFields } from "./_policy";

/**
 * Stable, alphabetically-sorted projection of every curated path on the
 * `aws_sqs_queue` policy map. Mirrors policy.Map iteration order in
 * presets's projection.go (sort.Strings on keys).
 */
export const POLICY: ReadonlyArray<FieldRow> = [
  { path: "arn", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "content_based_deduplication", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "deduplication_scope", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "delay_seconds", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "fifo_queue", role: "Tuning", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "AlwaysReplace" },
  { path: "fifo_throughput_limit", role: "Tuning", pillar: "Performance", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "id", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "kms_data_key_reuse_period_seconds", role: "Tuning", pillar: "Security", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "kms_master_key_id", role: "Wiring", pillar: "Security", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "MayReplace" },
  { path: "max_message_size", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "message_retention_seconds", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "name", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "AlwaysReplace" },
  { path: "name_prefix", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "AlwaysReplace" },
  { path: "policy", role: "Wiring", pillar: "Security", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "receive_wait_time_seconds", role: "Tuning", pillar: "Performance", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "redrive_allow_policy", role: "Wiring", pillar: "Reliability", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "redrive_policy", role: "Wiring", pillar: "Reliability", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "redrive_policy.deadLetterTargetArn", role: "Wiring", pillar: "Reliability", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "redrive_policy.maxReceiveCount", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "sqs_managed_sse_enabled", role: "Tuning", pillar: "Security", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "MayReplace" },
  { path: "tags", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Redacted", changeRisk: "Unknown" },
  { path: "tags_all", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Redacted", changeRisk: "Unknown" },
  { path: "url", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "visibility_timeout_seconds", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
];

/** Re-export so a single import covers the row type + the data. */
export type { FieldRow, FieldRole, FieldPillar, VisibilityPolicy, EditPolicy, SensitivityPolicy, ChangeRiskPolicy };

/**
 * visibleFields mirrors `policy.VisibleFieldsFor` in presets — every
 * curated row whose Visibility is UIVisible or SummaryVisible, with
 * Sensitive rows excluded. Returns rows in the same Path order as
 * POLICY, with `currentValue` resolved from `attrs` (null for
 * Sensitive rows by construction).
 */
export function visibleFields(attrs?: Record<string, unknown>) {
  return projectFields(POLICY, attrs, "visible");
}

/**
 * editableFields mirrors `policy.EditableFieldsFor` — the subset of
 * visibleFields whose EditPolicy permits a write (ChatSafe,
 * RequiresApproval, RelationshipOnly).
 */
export function editableFields(attrs?: Record<string, unknown>) {
  return projectFields(POLICY, attrs, "editable");
}
