// Code generated by cmd/imported-codegen; DO NOT EDIT.
// @generated
//
// TS projection of the Layer-2 field policy map for the
// `google_storage_bucket` Terraform resource. Mirrors
// pkg/composer/imported/policy/google_storage_bucket.policy.go in
// luthersystems/insideout-terraform-presets — the Go side is the source
// of truth; this file is regenerated by
// `imported-codegen policy-ts --out <dir>`.
//
// Consumers see a pure-data POLICY array (one row per curated
// attribute, in stable Path order) plus the two projection helpers
// VisibleFieldsFor / EditableFieldsFor as `visibleFields(attrs)` /
// `editableFields(attrs)`. No runtime dependency on presets — only the
// shared axis-enum types from `./_policy`.

import type {
  FieldRow,
  FieldRole,
  FieldPillar,
  VisibilityPolicy,
  EditPolicy,
  SensitivityPolicy,
  ChangeRiskPolicy,
} from "./_policy";
import { projectFields } from "./_policy";

/**
 * Stable, alphabetically-sorted projection of every curated path on the
 * `google_storage_bucket` policy map. Mirrors policy.Map iteration order in
 * presets's projection.go (sort.Strings on keys).
 */
export const POLICY: ReadonlyArray<FieldRow> = [
  { path: "autoclass.enabled", role: "Tuning", pillar: "Performance", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "cors.max_age_seconds", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "cors.method", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "cors.origin", role: "Tuning", pillar: "Security", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "cors.response_header", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "effective_labels", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Redacted", changeRisk: "Unknown" },
  { path: "encryption.default_kms_key_name", role: "Wiring", pillar: "Security", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "force_destroy", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "id", role: "Identity", pillar: "None", visibility: "SummaryVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "labels", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Redacted", changeRisk: "Unknown" },
  { path: "lifecycle_rule", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "location", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "AlwaysReplace" },
  { path: "logging.log_bucket", role: "Wiring", pillar: "Reliability", visibility: "SummaryVisible", edit: "RelationshipOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "logging.log_object_prefix", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "name", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "project", role: "Identity", pillar: "None", visibility: "UIVisible", edit: "Never", sensitivity: "Public", changeRisk: "AlwaysReplace" },
  { path: "public_access_prevention", role: "Tuning", pillar: "Security", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "MayReplace" },
  { path: "requester_pays", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "retention_policy.is_locked", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "MayReplace" },
  { path: "retention_policy.retention_period", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "rpo", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "self_link", role: "Identity", pillar: "None", visibility: "SummaryVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "soft_delete_policy.retention_duration_seconds", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "storage_class", role: "Tuning", pillar: "Performance", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "terraform_labels", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Redacted", changeRisk: "Unknown" },
  { path: "timeouts", role: "Tuning", pillar: "None", visibility: "Hidden", edit: "SystemOnly", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "uniform_bucket_level_access", role: "Tuning", pillar: "Security", visibility: "SummaryVisible", edit: "RequiresApproval", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "url", role: "Identity", pillar: "None", visibility: "SummaryVisible", edit: "Never", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "versioning.enabled", role: "Tuning", pillar: "Reliability", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "website.main_page_suffix", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
  { path: "website.not_found_page", role: "Tuning", pillar: "None", visibility: "SummaryVisible", edit: "ChatSafe", sensitivity: "Public", changeRisk: "Unknown" },
];

/** Re-export so a single import covers the row type + the data. */
export type { FieldRow, FieldRole, FieldPillar, VisibilityPolicy, EditPolicy, SensitivityPolicy, ChangeRiskPolicy };

/**
 * visibleFields mirrors `policy.VisibleFieldsFor` in presets — every
 * curated row whose Visibility is UIVisible or SummaryVisible, with
 * Sensitive rows excluded. Returns rows in the same Path order as
 * POLICY, with `currentValue` resolved from `attrs` (null for
 * Sensitive rows by construction).
 */
export function visibleFields(attrs?: Record<string, unknown>) {
  return projectFields(POLICY, attrs, "visible");
}

/**
 * editableFields mirrors `policy.EditableFieldsFor` — the subset of
 * visibleFields whose EditPolicy permits a write (ChatSafe,
 * RequiresApproval, RelationshipOnly).
 */
export function editableFields(attrs?: Record<string, unknown>) {
  return projectFields(POLICY, attrs, "editable");
}
