// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.GoogleComputeNetwork
//         + raw API struct computev1.Network
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package gcpdiscover

import (
	computev1 "google.golang.org/api/compute/v1"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

func mapComputeNetwork(b *computev1.Network, projectID string) *generated.GoogleComputeNetwork {
	out := &generated.GoogleComputeNetwork{}
	out.AutoCreateSubnetworks = generated.LiteralOf(b.AutoCreateSubnetworks)
	out.DeleteDefaultRoutesOnCreate = generated.LiteralOf(false)
	if b.Description != "" {
		out.Description = generated.LiteralOf(b.Description)
	}
	out.EnableUlaInternalIPV6 = generated.LiteralOf(b.EnableUlaInternalIpv6)
	if b.InternalIpv6Range != "" {
		out.InternalIPV6Range = generated.LiteralOf(b.InternalIpv6Range)
	}
	if b.Mtu != 0 {
		out.Mtu = generated.LiteralOf(float64(b.Mtu))
	}
	if b.Name != "" {
		out.Name = generated.LiteralOf(b.Name)
	}
	if b.NetworkFirewallPolicyEnforcementOrder != "" {
		out.NetworkFirewallPolicyEnforcementOrder = generated.LiteralOf(b.NetworkFirewallPolicyEnforcementOrder)
	}
	if projectID != "" {
		out.Project = generated.LiteralOf(projectID)
	}
	if b.RoutingConfig != nil && b.RoutingConfig.RoutingMode != "" {
		out.RoutingMode = generated.LiteralOf(b.RoutingConfig.RoutingMode)
	}
	return out
}
