// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.GooglePubsubTopic
//         + raw API struct pubsubv1.Topic
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package gcpdiscover

import (
	"strings"

	pubsubv1 "google.golang.org/api/pubsub/v1"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// pubsubTopicShortName extracts the short topic name from the API's
// fully-qualified resource name (projects/<p>/topics/<n>). Falls
// back to the input untouched if no "/" is present (defensive against
// unexpected shapes; in practice the API always returns the full
// form).
func pubsubTopicShortName(full string) string {
	if i := strings.LastIndex(full, "/"); i >= 0 {
		return full[i+1:]
	}
	return full
}

func mapPubsubTopic(b *pubsubv1.Topic, projectID string) *generated.GooglePubsubTopic {
	out := &generated.GooglePubsubTopic{}
	if b.KmsKeyName != "" {
		out.KMSKeyName = generated.LiteralOf(b.KmsKeyName)
	}
	if len(b.Labels) > 0 {
		labels := map[string]*generated.Value[string]{}
		for k, v := range b.Labels {
			if strings.HasPrefix(k, "goog-") || strings.HasPrefix(k, "goog_") {
				continue
			}
			labels[k] = generated.LiteralOf(v)
		}
		if len(labels) > 0 {
			out.Labels = labels
		}
	}

	if b.MessageRetentionDuration != "" {
		out.MessageRetentionDuration = generated.LiteralOf(b.MessageRetentionDuration)
	}
	out.Name = generated.LiteralOf(pubsubTopicShortName(b.Name))
	if projectID != "" {
		out.Project = generated.LiteralOf(projectID)
	}
	if b.IngestionDataSourceSettings != nil {
		out.IngestionDataSourceSettings = []generated.GooglePubsubTopicIngestionDataSourceSettings{enrichGooglePubsubTopicIngestionDataSourceSettings(b.IngestionDataSourceSettings)}
	}

	if b.MessageStoragePolicy != nil {
		out.MessageStoragePolicy = []generated.GooglePubsubTopicMessageStoragePolicy{enrichGooglePubsubTopicMessageStoragePolicy(b.MessageStoragePolicy)}
	}

	if b.SchemaSettings != nil {
		out.SchemaSettings = []generated.GooglePubsubTopicSchemaSettings{enrichGooglePubsubTopicSchemaSettings(b.SchemaSettings)}
	}

	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsAWSKinesis(b *pubsubv1.AwsKinesis) generated.GooglePubsubTopicIngestionDataSourceSettingsAWSKinesis {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsAWSKinesis{}
	if b.AwsRoleArn != "" {
		out.AWSRoleARN = generated.LiteralOf(b.AwsRoleArn)
	}
	if b.ConsumerArn != "" {
		out.ConsumerARN = generated.LiteralOf(b.ConsumerArn)
	}
	if b.GcpServiceAccount != "" {
		out.GCPServiceAccount = generated.LiteralOf(b.GcpServiceAccount)
	}
	if b.StreamArn != "" {
		out.StreamARN = generated.LiteralOf(b.StreamArn)
	}
	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorageAvroFormat(b *pubsubv1.AvroFormat) generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageAvroFormat {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageAvroFormat{}
	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStoragePubsubAvroFormat(b *pubsubv1.PubSubAvroFormat) generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStoragePubsubAvroFormat {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStoragePubsubAvroFormat{}
	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorageTextFormat(b *pubsubv1.TextFormat) generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageTextFormat {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageTextFormat{}
	if b.Delimiter != "" {
		out.Delimiter = generated.LiteralOf(b.Delimiter)
	}
	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorage(b *pubsubv1.CloudStorage) generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorage {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorage{}
	if b.Bucket != "" {
		out.Bucket = generated.LiteralOf(b.Bucket)
	}
	if b.MatchGlob != "" {
		out.MatchGlob = generated.LiteralOf(b.MatchGlob)
	}
	if b.MinimumObjectCreateTime != "" {
		out.MinimumObjectCreateTime = generated.LiteralOf(b.MinimumObjectCreateTime)
	}
	if b.AvroFormat != nil {
		out.AvroFormat = []generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageAvroFormat{enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorageAvroFormat(b.AvroFormat)}
	}

	if b.PubsubAvroFormat != nil {
		out.PubsubAvroFormat = []generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStoragePubsubAvroFormat{enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStoragePubsubAvroFormat(b.PubsubAvroFormat)}
	}

	if b.TextFormat != nil {
		out.TextFormat = []generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorageTextFormat{enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorageTextFormat(b.TextFormat)}
	}

	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettingsPlatformLogsSettings(b *pubsubv1.PlatformLogsSettings) generated.GooglePubsubTopicIngestionDataSourceSettingsPlatformLogsSettings {
	out := generated.GooglePubsubTopicIngestionDataSourceSettingsPlatformLogsSettings{}
	if b.Severity != "" {
		out.Severity = generated.LiteralOf(b.Severity)
	}
	return out
}

func enrichGooglePubsubTopicIngestionDataSourceSettings(b *pubsubv1.IngestionDataSourceSettings) generated.GooglePubsubTopicIngestionDataSourceSettings {
	out := generated.GooglePubsubTopicIngestionDataSourceSettings{}
	if b.AwsKinesis != nil {
		out.AWSKinesis = []generated.GooglePubsubTopicIngestionDataSourceSettingsAWSKinesis{enrichGooglePubsubTopicIngestionDataSourceSettingsAWSKinesis(b.AwsKinesis)}
	}

	if b.CloudStorage != nil {
		out.CloudStorage = []generated.GooglePubsubTopicIngestionDataSourceSettingsCloudStorage{enrichGooglePubsubTopicIngestionDataSourceSettingsCloudStorage(b.CloudStorage)}
	}

	if b.PlatformLogsSettings != nil {
		out.PlatformLogsSettings = []generated.GooglePubsubTopicIngestionDataSourceSettingsPlatformLogsSettings{enrichGooglePubsubTopicIngestionDataSourceSettingsPlatformLogsSettings(b.PlatformLogsSettings)}
	}

	return out
}

func enrichGooglePubsubTopicMessageStoragePolicy(b *pubsubv1.MessageStoragePolicy) generated.GooglePubsubTopicMessageStoragePolicy {
	out := generated.GooglePubsubTopicMessageStoragePolicy{}
	if len(b.AllowedPersistenceRegions) > 0 {
		out.AllowedPersistenceRegions = stringSliceToValues(b.AllowedPersistenceRegions)
	}

	return out
}

func enrichGooglePubsubTopicSchemaSettings(b *pubsubv1.SchemaSettings) generated.GooglePubsubTopicSchemaSettings {
	out := generated.GooglePubsubTopicSchemaSettings{}
	if b.Encoding != "" {
		out.Encoding = generated.LiteralOf(b.Encoding)
	}
	if b.Schema != "" {
		out.Schema = generated.LiteralOf(b.Schema)
	}
	return out
}
