// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.GooglePubsubSubscription
//         + raw API struct pubsubv1.Subscription
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package gcpdiscover

import (
	"strings"

	pubsubv1 "google.golang.org/api/pubsub/v1"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// pubsubSubscriptionShortName extracts the short subscription name
// from the API's fully-qualified resource name
// (projects/<p>/subscriptions/<n>). Falls back to the input
// untouched if no "/" is present (defensive against unexpected
// shapes).
func pubsubSubscriptionShortName(full string) string {
	if i := strings.LastIndex(full, "/"); i >= 0 {
		return full[i+1:]
	}
	return full
}

func mapPubsubSubscription(b *pubsubv1.Subscription, projectID string) *generated.GooglePubsubSubscription {
	out := &generated.GooglePubsubSubscription{}
	if b.AckDeadlineSeconds != 0 {
		out.AckDeadlineSeconds = generated.LiteralOf(b.AckDeadlineSeconds)
	}
	out.EnableExactlyOnceDelivery = generated.LiteralOf(b.EnableExactlyOnceDelivery)
	out.EnableMessageOrdering = generated.LiteralOf(b.EnableMessageOrdering)
	if b.Filter != "" {
		out.Filter = generated.LiteralOf(b.Filter)
	}
	if len(b.Labels) > 0 {
		labels := map[string]*generated.Value[string]{}
		for k, v := range b.Labels {
			if strings.HasPrefix(k, "goog-") || strings.HasPrefix(k, "goog_") {
				continue
			}
			labels[k] = generated.LiteralOf(v)
		}
		if len(labels) > 0 {
			out.Labels = labels
		}
	}

	if b.MessageRetentionDuration != "" {
		out.MessageRetentionDuration = generated.LiteralOf(b.MessageRetentionDuration)
	}
	out.Name = generated.LiteralOf(pubsubSubscriptionShortName(b.Name))
	if projectID != "" {
		out.Project = generated.LiteralOf(projectID)
	}
	out.RetainAckedMessages = generated.LiteralOf(b.RetainAckedMessages)
	if b.Topic != "" {
		out.Topic = generated.LiteralOf(b.Topic)
	}
	if b.BigqueryConfig != nil {
		out.BigqueryConfig = []generated.GooglePubsubSubscriptionBigqueryConfig{enrichGooglePubsubSubscriptionBigqueryConfig(b.BigqueryConfig)}
	}

	if b.CloudStorageConfig != nil {
		out.CloudStorageConfig = []generated.GooglePubsubSubscriptionCloudStorageConfig{enrichGooglePubsubSubscriptionCloudStorageConfig(b.CloudStorageConfig)}
	}

	if b.DeadLetterPolicy != nil {
		out.DeadLetterPolicy = []generated.GooglePubsubSubscriptionDeadLetterPolicy{enrichGooglePubsubSubscriptionDeadLetterPolicy(b.DeadLetterPolicy)}
	}

	if b.ExpirationPolicy != nil {
		out.ExpirationPolicy = []generated.GooglePubsubSubscriptionExpirationPolicy{enrichGooglePubsubSubscriptionExpirationPolicy(b.ExpirationPolicy)}
	}

	if b.PushConfig != nil {
		out.PushConfig = []generated.GooglePubsubSubscriptionPushConfig{enrichGooglePubsubSubscriptionPushConfig(b.PushConfig)}
	}

	if b.RetryPolicy != nil {
		out.RetryPolicy = []generated.GooglePubsubSubscriptionRetryPolicy{enrichGooglePubsubSubscriptionRetryPolicy(b.RetryPolicy)}
	}

	return out
}

func enrichGooglePubsubSubscriptionBigqueryConfig(b *pubsubv1.BigQueryConfig) generated.GooglePubsubSubscriptionBigqueryConfig {
	out := generated.GooglePubsubSubscriptionBigqueryConfig{}
	out.DropUnknownFields = generated.LiteralOf(b.DropUnknownFields)
	if b.ServiceAccountEmail != "" {
		out.ServiceAccountEmail = generated.LiteralOf(b.ServiceAccountEmail)
	}
	if b.Table != "" {
		out.Table = generated.LiteralOf(b.Table)
	}
	out.UseTableSchema = generated.LiteralOf(b.UseTableSchema)
	out.UseTopicSchema = generated.LiteralOf(b.UseTopicSchema)
	out.WriteMetadata = generated.LiteralOf(b.WriteMetadata)
	return out
}

func enrichGooglePubsubSubscriptionCloudStorageConfigAvroConfig(b *pubsubv1.AvroConfig) generated.GooglePubsubSubscriptionCloudStorageConfigAvroConfig {
	out := generated.GooglePubsubSubscriptionCloudStorageConfigAvroConfig{}
	out.UseTopicSchema = generated.LiteralOf(b.UseTopicSchema)
	out.WriteMetadata = generated.LiteralOf(b.WriteMetadata)
	return out
}

func enrichGooglePubsubSubscriptionCloudStorageConfig(b *pubsubv1.CloudStorageConfig) generated.GooglePubsubSubscriptionCloudStorageConfig {
	out := generated.GooglePubsubSubscriptionCloudStorageConfig{}
	if b.Bucket != "" {
		out.Bucket = generated.LiteralOf(b.Bucket)
	}
	if b.FilenameDatetimeFormat != "" {
		out.FilenameDatetimeFormat = generated.LiteralOf(b.FilenameDatetimeFormat)
	}
	if b.FilenamePrefix != "" {
		out.FilenamePrefix = generated.LiteralOf(b.FilenamePrefix)
	}
	if b.FilenameSuffix != "" {
		out.FilenameSuffix = generated.LiteralOf(b.FilenameSuffix)
	}
	if b.MaxBytes != 0 {
		out.MaxBytes = generated.LiteralOf(b.MaxBytes)
	}
	if b.MaxDuration != "" {
		out.MaxDuration = generated.LiteralOf(b.MaxDuration)
	}
	if b.MaxMessages != 0 {
		out.MaxMessages = generated.LiteralOf(b.MaxMessages)
	}
	if b.ServiceAccountEmail != "" {
		out.ServiceAccountEmail = generated.LiteralOf(b.ServiceAccountEmail)
	}
	if b.AvroConfig != nil {
		out.AvroConfig = []generated.GooglePubsubSubscriptionCloudStorageConfigAvroConfig{enrichGooglePubsubSubscriptionCloudStorageConfigAvroConfig(b.AvroConfig)}
	}

	return out
}

func enrichGooglePubsubSubscriptionDeadLetterPolicy(b *pubsubv1.DeadLetterPolicy) generated.GooglePubsubSubscriptionDeadLetterPolicy {
	out := generated.GooglePubsubSubscriptionDeadLetterPolicy{}
	if b.DeadLetterTopic != "" {
		out.DeadLetterTopic = generated.LiteralOf(b.DeadLetterTopic)
	}
	if b.MaxDeliveryAttempts != 0 {
		out.MaxDeliveryAttempts = generated.LiteralOf(b.MaxDeliveryAttempts)
	}
	return out
}

func enrichGooglePubsubSubscriptionExpirationPolicy(b *pubsubv1.ExpirationPolicy) generated.GooglePubsubSubscriptionExpirationPolicy {
	out := generated.GooglePubsubSubscriptionExpirationPolicy{}
	if b.Ttl != "" {
		out.TTL = generated.LiteralOf(b.Ttl)
	}
	return out
}

func enrichGooglePubsubSubscriptionPushConfigNoWrapper(b *pubsubv1.NoWrapper) generated.GooglePubsubSubscriptionPushConfigNoWrapper {
	out := generated.GooglePubsubSubscriptionPushConfigNoWrapper{}
	out.WriteMetadata = generated.LiteralOf(b.WriteMetadata)
	return out
}

func enrichGooglePubsubSubscriptionPushConfigOIDCToken(b *pubsubv1.OidcToken) generated.GooglePubsubSubscriptionPushConfigOIDCToken {
	out := generated.GooglePubsubSubscriptionPushConfigOIDCToken{}
	if b.Audience != "" {
		out.Audience = generated.LiteralOf(b.Audience)
	}
	if b.ServiceAccountEmail != "" {
		out.ServiceAccountEmail = generated.LiteralOf(b.ServiceAccountEmail)
	}
	return out
}

func enrichGooglePubsubSubscriptionPushConfig(b *pubsubv1.PushConfig) generated.GooglePubsubSubscriptionPushConfig {
	out := generated.GooglePubsubSubscriptionPushConfig{}
	if len(b.Attributes) > 0 {
		m := map[string]*generated.Value[string]{}
		for k, v := range b.Attributes {
			m[k] = generated.LiteralOf(v)
		}
		out.Attributes = m
	}

	if b.PushEndpoint != "" {
		out.PushEndpoint = generated.LiteralOf(b.PushEndpoint)
	}
	if b.NoWrapper != nil {
		out.NoWrapper = []generated.GooglePubsubSubscriptionPushConfigNoWrapper{enrichGooglePubsubSubscriptionPushConfigNoWrapper(b.NoWrapper)}
	}

	if b.OidcToken != nil {
		out.OIDCToken = []generated.GooglePubsubSubscriptionPushConfigOIDCToken{enrichGooglePubsubSubscriptionPushConfigOIDCToken(b.OidcToken)}
	}

	return out
}

func enrichGooglePubsubSubscriptionRetryPolicy(b *pubsubv1.RetryPolicy) generated.GooglePubsubSubscriptionRetryPolicy {
	out := generated.GooglePubsubSubscriptionRetryPolicy{}
	if b.MaximumBackoff != "" {
		out.MaximumBackoff = generated.LiteralOf(b.MaximumBackoff)
	}
	if b.MinimumBackoff != "" {
		out.MinimumBackoff = generated.LiteralOf(b.MinimumBackoff)
	}
	return out
}
