// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.GoogleSecretManagerSecret
//         + raw API struct secretmanagerv1.Secret
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package gcpdiscover

import (
	"strings"

	secretmanagerv1 "google.golang.org/api/secretmanager/v1"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// secretShortID extracts the short secret_id from the API's
// fully-qualified resource name (projects/<p>/secrets/<n>). Falls
// back to the input untouched if no "/" is present.
func secretShortID(full string) string {
	if i := strings.LastIndex(full, "/"); i >= 0 {
		return full[i+1:]
	}
	return full
}

func mapSecretManagerSecret(b *secretmanagerv1.Secret, projectID string) *generated.GoogleSecretManagerSecret {
	out := &generated.GoogleSecretManagerSecret{}
	if len(b.Annotations) > 0 {
		m := map[string]*generated.Value[string]{}
		for k, v := range b.Annotations {
			m[k] = generated.LiteralOf(v)
		}
		out.Annotations = m
	}

	if b.ExpireTime != "" {
		out.ExpireTime = generated.LiteralOf(b.ExpireTime)
	}
	if len(b.Labels) > 0 {
		labels := map[string]*generated.Value[string]{}
		for k, v := range b.Labels {
			if strings.HasPrefix(k, "goog-") || strings.HasPrefix(k, "goog_") {
				continue
			}
			labels[k] = generated.LiteralOf(v)
		}
		if len(labels) > 0 {
			out.Labels = labels
		}
	}

	if projectID != "" {
		out.Project = generated.LiteralOf(projectID)
	}
	out.SecretID = generated.LiteralOf(secretShortID(b.Name))
	if len(b.VersionAliases) > 0 {
		m := map[string]*generated.Value[string]{}
		for k, v := range b.VersionAliases {
			m[k] = generated.LiteralOf(v)
		}
		out.VersionAliases = m
	}

	if b.VersionDestroyTtl != "" {
		out.VersionDestroyTTL = generated.LiteralOf(b.VersionDestroyTtl)
	}
	if b.Replication != nil {
		out.Replication = []generated.GoogleSecretManagerSecretReplication{enrichGoogleSecretManagerSecretReplication(b.Replication)}
	}

	if b.Rotation != nil {
		out.Rotation = []generated.GoogleSecretManagerSecretRotation{enrichGoogleSecretManagerSecretRotation(b.Rotation)}
	}

	if len(b.Topics) > 0 {
		blocks := make([]generated.GoogleSecretManagerSecretTopics, 0, len(b.Topics))
		for _, x := range b.Topics {
			if x == nil {
				continue
			}
			blocks = append(blocks, enrichGoogleSecretManagerSecretTopics(x))
		}
		if len(blocks) > 0 {
			out.Topics = blocks
		}
	}

	return out
}

func enrichGoogleSecretManagerSecretReplicationAutoCustomerManagedEncryption(b *secretmanagerv1.CustomerManagedEncryption) generated.GoogleSecretManagerSecretReplicationAutoCustomerManagedEncryption {
	out := generated.GoogleSecretManagerSecretReplicationAutoCustomerManagedEncryption{}
	if b.KmsKeyName != "" {
		out.KMSKeyName = generated.LiteralOf(b.KmsKeyName)
	}
	return out
}

func enrichGoogleSecretManagerSecretReplicationAuto(b *secretmanagerv1.Automatic) generated.GoogleSecretManagerSecretReplicationAuto {
	out := generated.GoogleSecretManagerSecretReplicationAuto{}
	if b.CustomerManagedEncryption != nil {
		out.CustomerManagedEncryption = []generated.GoogleSecretManagerSecretReplicationAutoCustomerManagedEncryption{enrichGoogleSecretManagerSecretReplicationAutoCustomerManagedEncryption(b.CustomerManagedEncryption)}
	}

	return out
}

func enrichGoogleSecretManagerSecretReplicationUserManagedReplicasCustomerManagedEncryption(b *secretmanagerv1.CustomerManagedEncryption) generated.GoogleSecretManagerSecretReplicationUserManagedReplicasCustomerManagedEncryption {
	out := generated.GoogleSecretManagerSecretReplicationUserManagedReplicasCustomerManagedEncryption{}
	if b.KmsKeyName != "" {
		out.KMSKeyName = generated.LiteralOf(b.KmsKeyName)
	}
	return out
}

func enrichGoogleSecretManagerSecretReplicationUserManagedReplicas(b *secretmanagerv1.Replica) generated.GoogleSecretManagerSecretReplicationUserManagedReplicas {
	out := generated.GoogleSecretManagerSecretReplicationUserManagedReplicas{}
	if b.Location != "" {
		out.Location = generated.LiteralOf(b.Location)
	}
	if b.CustomerManagedEncryption != nil {
		out.CustomerManagedEncryption = []generated.GoogleSecretManagerSecretReplicationUserManagedReplicasCustomerManagedEncryption{enrichGoogleSecretManagerSecretReplicationUserManagedReplicasCustomerManagedEncryption(b.CustomerManagedEncryption)}
	}

	return out
}

func enrichGoogleSecretManagerSecretReplicationUserManaged(b *secretmanagerv1.UserManaged) generated.GoogleSecretManagerSecretReplicationUserManaged {
	out := generated.GoogleSecretManagerSecretReplicationUserManaged{}
	if len(b.Replicas) > 0 {
		blocks := make([]generated.GoogleSecretManagerSecretReplicationUserManagedReplicas, 0, len(b.Replicas))
		for _, x := range b.Replicas {
			if x == nil {
				continue
			}
			blocks = append(blocks, enrichGoogleSecretManagerSecretReplicationUserManagedReplicas(x))
		}
		if len(blocks) > 0 {
			out.Replicas = blocks
		}
	}

	return out
}

func enrichGoogleSecretManagerSecretReplication(b *secretmanagerv1.Replication) generated.GoogleSecretManagerSecretReplication {
	out := generated.GoogleSecretManagerSecretReplication{}
	if b.Automatic != nil {
		out.Auto = []generated.GoogleSecretManagerSecretReplicationAuto{enrichGoogleSecretManagerSecretReplicationAuto(b.Automatic)}
	}

	if b.UserManaged != nil {
		out.UserManaged = []generated.GoogleSecretManagerSecretReplicationUserManaged{enrichGoogleSecretManagerSecretReplicationUserManaged(b.UserManaged)}
	}

	return out
}

func enrichGoogleSecretManagerSecretRotation(b *secretmanagerv1.Rotation) generated.GoogleSecretManagerSecretRotation {
	out := generated.GoogleSecretManagerSecretRotation{}
	if b.NextRotationTime != "" {
		out.NextRotationTime = generated.LiteralOf(b.NextRotationTime)
	}
	if b.RotationPeriod != "" {
		out.RotationPeriod = generated.LiteralOf(b.RotationPeriod)
	}
	return out
}

func enrichGoogleSecretManagerSecretTopics(b *secretmanagerv1.Topic) generated.GoogleSecretManagerSecretTopics {
	out := generated.GoogleSecretManagerSecretTopics{}
	if b.Name != "" {
		out.Name = generated.LiteralOf(b.Name)
	}
	return out
}
