// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.GoogleStorageBucket
//         + raw API struct storagev1.Bucket
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package gcpdiscover

import (
	"strings"

	storagev1 "google.golang.org/api/storage/v1"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// billingRequesterPays flattens the nullable Billing.RequesterPays
// pointer into a default-false bool. Used by the requester_pays
// override; kept private to the generated file because no other
// type's mapping needs it.
func billingRequesterPays(b *storagev1.BucketBilling) bool {
	if b == nil {
		return false
	}
	return b.RequesterPays
}

func mapStorageBucket(b *storagev1.Bucket, projectID string) *generated.GoogleStorageBucket {
	out := &generated.GoogleStorageBucket{}
	out.DefaultEventBasedHold = generated.LiteralOf(b.DefaultEventBasedHold)
	out.EnableObjectRetention = generated.LiteralOf(b.ObjectRetention != nil && b.ObjectRetention.Mode == "Enabled")
	out.ForceDestroy = generated.LiteralOf(false)
	if len(b.Labels) > 0 {
		labels := map[string]*generated.Value[string]{}
		for k, v := range b.Labels {
			if strings.HasPrefix(k, "goog-") || strings.HasPrefix(k, "goog_") {
				continue
			}
			labels[k] = generated.LiteralOf(v)
		}
		if len(labels) > 0 {
			out.Labels = labels
		}
	}

	out.Location = generated.LiteralOf(strings.ToUpper(b.Location))
	if b.Name != "" {
		out.Name = generated.LiteralOf(b.Name)
	}
	if projectID != "" {
		out.Project = generated.LiteralOf(projectID)
	}
	if b.IamConfiguration != nil && b.IamConfiguration.PublicAccessPrevention != "" {
		out.PublicAccessPrevention = generated.LiteralOf(b.IamConfiguration.PublicAccessPrevention)
	}
	out.RequesterPays = generated.LiteralOf(billingRequesterPays(b.Billing))
	if b.Rpo != "" {
		out.Rpo = generated.LiteralOf(b.Rpo)
	}
	if b.StorageClass != "" {
		out.StorageClass = generated.LiteralOf(b.StorageClass)
	}
	if b.IamConfiguration != nil && b.IamConfiguration.UniformBucketLevelAccess != nil {
		out.UniformBucketLevelAccess = generated.LiteralOf(b.IamConfiguration.UniformBucketLevelAccess.Enabled)
	}
	if b.Autoclass != nil {
		out.Autoclass = []generated.GoogleStorageBucketAutoclass{enrichGoogleStorageBucketAutoclass(b.Autoclass)}
	}

	if len(b.Cors) > 0 {
		blocks := make([]generated.GoogleStorageBucketCors, 0, len(b.Cors))
		for _, x := range b.Cors {
			if x == nil {
				continue
			}
			blocks = append(blocks, enrichGoogleStorageBucketCors(x))
		}
		if len(blocks) > 0 {
			out.Cors = blocks
		}
	}

	if b.CustomPlacementConfig != nil && len(b.CustomPlacementConfig.DataLocations) > 0 {
		out.CustomPlacementConfig = []generated.GoogleStorageBucketCustomPlacementConfig{enrichGoogleStorageBucketCustomPlacementConfig(b.CustomPlacementConfig)}
	}

	if b.Encryption != nil && b.Encryption.DefaultKmsKeyName != "" {
		out.Encryption = []generated.GoogleStorageBucketEncryption{enrichGoogleStorageBucketEncryption(b.Encryption)}
	}

	if b.HierarchicalNamespace != nil {
		out.HierarchicalNamespace = []generated.GoogleStorageBucketHierarchicalNamespace{enrichGoogleStorageBucketHierarchicalNamespace(b.HierarchicalNamespace)}
	}

	if b.Lifecycle != nil && len(b.Lifecycle.Rule) > 0 {
		blocks := make([]generated.GoogleStorageBucketLifecycleRule, 0, len(b.Lifecycle.Rule))
		for _, r := range b.Lifecycle.Rule {
			if r == nil {
				continue
			}
			blocks = append(blocks, enrichGoogleStorageBucketLifecycleRule(r))
		}
		if len(blocks) > 0 {
			out.LifecycleRule = blocks
		}
	}

	if b.Logging != nil {
		out.Logging = []generated.GoogleStorageBucketLogging{enrichGoogleStorageBucketLogging(b.Logging)}
	}

	if b.RetentionPolicy != nil {
		out.RetentionPolicy = []generated.GoogleStorageBucketRetentionPolicy{enrichGoogleStorageBucketRetentionPolicy(b.RetentionPolicy)}
	}

	if b.SoftDeletePolicy != nil && b.SoftDeletePolicy.RetentionDurationSeconds > 0 {
		out.SoftDeletePolicy = []generated.GoogleStorageBucketSoftDeletePolicy{enrichGoogleStorageBucketSoftDeletePolicy(b.SoftDeletePolicy)}
	}

	if b.Versioning != nil {
		out.Versioning = []generated.GoogleStorageBucketVersioning{enrichGoogleStorageBucketVersioning(b.Versioning)}
	}

	if b.Website != nil && (b.Website.MainPageSuffix != "" || b.Website.NotFoundPage != "") {
		out.Website = []generated.GoogleStorageBucketWebsite{enrichGoogleStorageBucketWebsite(b.Website)}
	}

	return out
}

func enrichGoogleStorageBucketAutoclass(b *storagev1.BucketAutoclass) generated.GoogleStorageBucketAutoclass {
	out := generated.GoogleStorageBucketAutoclass{}
	out.Enabled = generated.LiteralOf(b.Enabled)
	if b.TerminalStorageClass != "" {
		out.TerminalStorageClass = generated.LiteralOf(b.TerminalStorageClass)
	}
	return out
}

func enrichGoogleStorageBucketCors(b *storagev1.BucketCors) generated.GoogleStorageBucketCors {
	out := generated.GoogleStorageBucketCors{}
	if b.MaxAgeSeconds != 0 {
		out.MaxAgeSeconds = generated.LiteralOf(b.MaxAgeSeconds)
	}
	if len(b.Method) > 0 {
		out.Method = stringSliceToValues(b.Method)
	}

	if len(b.Origin) > 0 {
		out.Origin = stringSliceToValues(b.Origin)
	}

	if len(b.ResponseHeader) > 0 {
		out.ResponseHeader = stringSliceToValues(b.ResponseHeader)
	}

	return out
}

func enrichGoogleStorageBucketCustomPlacementConfig(b *storagev1.BucketCustomPlacementConfig) generated.GoogleStorageBucketCustomPlacementConfig {
	out := generated.GoogleStorageBucketCustomPlacementConfig{}
	if len(b.DataLocations) > 0 {
		out.DataLocations = stringSliceToValues(b.DataLocations)
	}

	return out
}

func enrichGoogleStorageBucketEncryption(b *storagev1.BucketEncryption) generated.GoogleStorageBucketEncryption {
	out := generated.GoogleStorageBucketEncryption{}
	out.DefaultKMSKeyName = generated.LiteralOf(b.DefaultKmsKeyName)
	return out
}

func enrichGoogleStorageBucketHierarchicalNamespace(b *storagev1.BucketHierarchicalNamespace) generated.GoogleStorageBucketHierarchicalNamespace {
	out := generated.GoogleStorageBucketHierarchicalNamespace{}
	out.Enabled = generated.LiteralOf(b.Enabled)
	return out
}

func enrichGoogleStorageBucketLifecycleRuleAction(b *storagev1.BucketLifecycleRuleAction) generated.GoogleStorageBucketLifecycleRuleAction {
	out := generated.GoogleStorageBucketLifecycleRuleAction{}
	if b.StorageClass != "" {
		out.StorageClass = generated.LiteralOf(b.StorageClass)
	}
	if b.Type != "" {
		out.Type_ = generated.LiteralOf(b.Type)
	}
	return out
}

func enrichGoogleStorageBucketLifecycleRuleCondition(b *storagev1.BucketLifecycleRuleCondition) generated.GoogleStorageBucketLifecycleRuleCondition {
	out := generated.GoogleStorageBucketLifecycleRuleCondition{}
	if b.Age != nil {
		out.Age = generated.LiteralOf(float64(*b.Age))
	}
	if b.CreatedBefore != "" {
		out.CreatedBefore = generated.LiteralOf(b.CreatedBefore)
	}
	if b.CustomTimeBefore != "" {
		out.CustomTimeBefore = generated.LiteralOf(b.CustomTimeBefore)
	}
	if b.DaysSinceCustomTime != 0 {
		out.DaysSinceCustomTime = generated.LiteralOf(float64(b.DaysSinceCustomTime))
	}
	if b.DaysSinceNoncurrentTime != 0 {
		out.DaysSinceNoncurrentTime = generated.LiteralOf(float64(b.DaysSinceNoncurrentTime))
	}
	if len(b.MatchesPrefix) > 0 {
		out.MatchesPrefix = stringSliceToValues(b.MatchesPrefix)
	}

	if len(b.MatchesStorageClass) > 0 {
		out.MatchesStorageClass = stringSliceToValues(b.MatchesStorageClass)
	}

	if len(b.MatchesSuffix) > 0 {
		out.MatchesSuffix = stringSliceToValues(b.MatchesSuffix)
	}

	if b.NoncurrentTimeBefore != "" {
		out.NoncurrentTimeBefore = generated.LiteralOf(b.NoncurrentTimeBefore)
	}
	if b.NumNewerVersions != 0 {
		out.NumNewerVersions = generated.LiteralOf(float64(b.NumNewerVersions))
	}
	if b.IsLive != nil {
		out.WithState = generated.LiteralOf(map[bool]string{true: "LIVE", false: "ARCHIVED"}[*b.IsLive])
	}
	return out
}

func enrichGoogleStorageBucketLifecycleRule(b *storagev1.BucketLifecycleRule) generated.GoogleStorageBucketLifecycleRule {
	out := generated.GoogleStorageBucketLifecycleRule{}
	if b.Action != nil {
		out.Action = []generated.GoogleStorageBucketLifecycleRuleAction{enrichGoogleStorageBucketLifecycleRuleAction(b.Action)}
	}

	if b.Condition != nil {
		out.Condition = []generated.GoogleStorageBucketLifecycleRuleCondition{enrichGoogleStorageBucketLifecycleRuleCondition(b.Condition)}
	}

	return out
}

func enrichGoogleStorageBucketLogging(b *storagev1.BucketLogging) generated.GoogleStorageBucketLogging {
	out := generated.GoogleStorageBucketLogging{}
	out.LogBucket = generated.LiteralOf(b.LogBucket)
	if b.LogObjectPrefix != "" {
		out.LogObjectPrefix = generated.LiteralOf(b.LogObjectPrefix)
	}
	return out
}

func enrichGoogleStorageBucketRetentionPolicy(b *storagev1.BucketRetentionPolicy) generated.GoogleStorageBucketRetentionPolicy {
	out := generated.GoogleStorageBucketRetentionPolicy{}
	out.IsLocked = generated.LiteralOf(b.IsLocked)
	if b.RetentionPeriod != 0 {
		out.RetentionPeriod = generated.LiteralOf(b.RetentionPeriod)
	}
	return out
}

func enrichGoogleStorageBucketSoftDeletePolicy(b *storagev1.BucketSoftDeletePolicy) generated.GoogleStorageBucketSoftDeletePolicy {
	out := generated.GoogleStorageBucketSoftDeletePolicy{}
	if b.RetentionDurationSeconds != 0 {
		out.RetentionDurationSeconds = generated.LiteralOf(b.RetentionDurationSeconds)
	}
	return out
}

func enrichGoogleStorageBucketVersioning(b *storagev1.BucketVersioning) generated.GoogleStorageBucketVersioning {
	out := generated.GoogleStorageBucketVersioning{}
	out.Enabled = generated.LiteralOf(b.Enabled)
	return out
}

func enrichGoogleStorageBucketWebsite(b *storagev1.BucketWebsite) generated.GoogleStorageBucketWebsite {
	out := generated.GoogleStorageBucketWebsite{}
	if b.MainPageSuffix != "" {
		out.MainPageSuffix = generated.LiteralOf(b.MainPageSuffix)
	}
	if b.NotFoundPage != "" {
		out.NotFoundPage = generated.LiteralOf(b.NotFoundPage)
	}
	return out
}
