// Code generated by cmd/imported-codegen; DO NOT EDIT.
// @generated
//
// Shared axis-enum types and projection runtime for per-type policy.ts
// files. Mirrors pkg/composer/imported/policy/axes.go +
// projection.go's filter/walker semantics — kept in lockstep with the
// Go source of truth via the policy-ts emitter (presets#400 follow-up).

/** Structural purpose. Mirrors `policy.FieldRole`. */
export type FieldRole = "Identity" | "Wiring" | "Tuning";

/**
 * Operational concern. Mirrors `policy.FieldPillar`. "None" is the
 * empty-string sentinel from the Go side ("" / PillarNone) serialised
 * to a named string for readability on the wire.
 */
export type FieldPillar = "None" | "Security" | "Performance" | "Reliability";

/** Visibility. Mirrors `policy.VisibilityPolicy`. */
export type VisibilityPolicy = "Hidden" | "UIVisible" | "SummaryVisible";

/** Edit policy. Mirrors `policy.EditPolicy`. */
export type EditPolicy =
  | "Never"
  | "ChatSafe"
  | "RequiresApproval"
  | "RelationshipOnly"
  | "SystemOnly";

/**
 * Sensitivity. Mirrors `policy.SensitivityPolicy`. "Public" is the
 * default for unset axes (Go's empty-string-is-Public synonym).
 */
export type SensitivityPolicy = "Public" | "Redacted" | "Sensitive";

/**
 * Change risk. Mirrors `policy.ChangeRiskPolicy`. "Unknown" is the
 * default for unset axes (Go's empty-string-is-Unknown synonym).
 */
export type ChangeRiskPolicy =
  | "InPlace"
  | "MayReplace"
  | "AlwaysReplace"
  | "Unknown";

/**
 * One row of the projection. Mirrors `policy.FieldView` minus
 * `currentValue` which is populated at projection time by
 * `projectFields`. Shape stays stable so consumers can downcast in TS
 * without `as` gymnastics.
 */
export interface FieldRow {
  path: string;
  role: FieldRole;
  pillar: FieldPillar;
  visibility: VisibilityPolicy;
  edit: EditPolicy;
  sensitivity: SensitivityPolicy;
  changeRisk: ChangeRiskPolicy;
}

/**
 * Projection row enriched with `currentValue` walked from the input
 * attrs. Matches `policy.FieldView` shape on the Go side; the value
 * type is `unknown` because the schema-aware Zod type is in the
 * per-type module, not here.
 */
export interface ProjectedRow extends FieldRow {
  currentValue: unknown;
}

/**
 * walkValue is the TS twin of `walkValue` in presets's
 * projection.go: descend a dotted path through an object / array
 * tree. Arrays fan out and the leaves are flattened into a single
 * array. Returns null when any segment fails to resolve.
 */
function walkValue(v: unknown, path: string): unknown {
  if (path === "") return v;
  if (v && typeof v === "object" && !Array.isArray(v)) {
    const idx = path.indexOf(".");
    const head = idx >= 0 ? path.slice(0, idx) : path;
    const rest = idx >= 0 ? path.slice(idx + 1) : "";
    const obj = v as Record<string, unknown>;
    if (!(head in obj)) return null;
    return walkValue(obj[head], rest);
  }
  if (Array.isArray(v)) {
    const out: unknown[] = [];
    for (const elem of v) {
      const r = walkValue(elem, path);
      if (r == null) continue;
      if (Array.isArray(r)) out.push(...r);
      else out.push(r);
    }
    return out.length === 0 ? null : out;
  }
  return null;
}

function resolveAttrPath(
  attrs: Record<string, unknown> | undefined,
  dottedPath: string,
): unknown {
  if (!attrs) return null;
  if (dottedPath === "") return attrs;
  return walkValue(attrs, dottedPath);
}

function passesVisible(r: FieldRow): boolean {
  if (r.sensitivity === "Sensitive") return false;
  return r.visibility === "UIVisible" || r.visibility === "SummaryVisible";
}

function passesEditable(r: FieldRow): boolean {
  if (!passesVisible(r)) return false;
  return (
    r.edit === "ChatSafe" ||
    r.edit === "RequiresApproval" ||
    r.edit === "RelationshipOnly"
  );
}

/**
 * projectFields is the shared filter+resolve runtime used by every
 * per-type module's `visibleFields` / `editableFields`. Splitting it
 * out keeps the generated per-type files small (one POLICY array, two
 * thin wrappers) and the filter logic in one place.
 */
export function projectFields(
  rows: ReadonlyArray<FieldRow>,
  attrs: Record<string, unknown> | undefined,
  mode: "visible" | "editable",
): ProjectedRow[] {
  const keep = mode === "visible" ? passesVisible : passesEditable;
  const out: ProjectedRow[] = [];
  for (const r of rows) {
    if (!keep(r)) continue;
    const cur = r.sensitivity === "Sensitive" ? null : resolveAttrPath(attrs, r.path);
    out.push({ ...r, currentValue: cur });
  }
  return out;
}
