package genconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclwrite"
)

// parseSingleResourceBody parses a one-resource HCL snippet and returns the
// resource block's body for unimportableReason's per-type assertions.
func parseSingleResourceBody(t *testing.T, src string) *hclwrite.Body {
	t.Helper()
	f, diags := hclwrite.ParseConfig([]byte(src), "test.tf", hcl.Pos{Line: 1, Column: 1})
	if diags.HasErrors() {
		t.Fatalf("parse: %s", diags.Error())
	}
	for _, blk := range f.Body().Blocks() {
		if blk.Type() == "resource" {
			return blk.Body()
		}
	}
	t.Fatalf("no resource block in snippet:\n%s", src)
	return nil
}

// writeImports writes an imports.tf into dir for the prune tests.
func writeImports(t *testing.T, dir, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, importsFile), []byte(body), 0o644); err != nil {
		t.Fatalf("write imports.tf: %v", err)
	}
}

// TestPruneUnimportable_DropsAWSManagedKMSAlias pins the #708 root failure:
// an aws_kms_alias whose name carries the reserved alias/aws/ prefix is
// AWS-managed and the provider rejects it. It must be dropped — body and
// import block — while a customer alias of the same type is preserved.
func TestPruneUnimportable_DropsAWSManagedKMSAlias(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeImports(t, dir, `import {
  to = aws_kms_alias.alias_aws_rds
  id = "alias/aws/rds@us-east-1"
}

import {
  to = aws_kms_alias.customer
  id = "alias/io-foo@us-east-1"
}
`)
	generated := []byte(`resource "aws_kms_alias" "alias_aws_rds" {
  name          = "alias/aws/rds"
  target_key_id = "abc"
}

resource "aws_kms_alias" "customer" {
  name          = "alias/io-foo"
  target_key_id = "def"
}
`)
	res, err := pruneUnimportable(dir, generated)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 1 {
		t.Fatalf("want 1 skipped, got %d: %+v", len(res.Skipped), res.Skipped)
	}
	if res.Skipped[0].Address != "aws_kms_alias.alias_aws_rds" || res.Skipped[0].Reason != reasonAWSManagedKMSAlias {
		t.Errorf("unexpected skipped entry: %+v", res.Skipped[0])
	}
	if res.Skipped[0].ImportID != "alias/aws/rds@us-east-1" {
		t.Errorf("import id not captured: %q", res.Skipped[0].ImportID)
	}
	got := string(res.HCL)
	if strings.Contains(got, `"alias_aws_rds"`) {
		t.Errorf("AWS-managed alias block must be removed\n%s", got)
	}
	if !strings.Contains(got, `"customer"`) {
		t.Errorf("customer alias must be preserved\n%s", got)
	}
	importsOut, err := os.ReadFile(filepath.Join(dir, importsFile))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(importsOut), "alias_aws_rds") {
		t.Errorf("managed import block must be removed from imports.tf\n%s", importsOut)
	}
	if !strings.Contains(string(importsOut), "aws_kms_alias.customer") {
		t.Errorf("customer import block must be preserved\n%s", importsOut)
	}
}

// TestPruneUnimportable_DropsServiceManagedENI pins that a service-managed
// ENI (interface_type=nat_gateway) is dropped while a standard ENI survives.
func TestPruneUnimportable_DropsServiceManagedENI(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeImports(t, dir, `import {
  to = aws_network_interface.nat
  id = "eni-nat@us-east-1"
}

import {
  to = aws_network_interface.standard
  id = "eni-std@us-east-1"
}
`)
	generated := []byte(`resource "aws_network_interface" "nat" {
  interface_type = "nat_gateway"
}

resource "aws_network_interface" "standard" {
  private_ips = ["10.0.0.5"]
}
`)
	res, err := pruneUnimportable(dir, generated)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 1 || res.Skipped[0].Reason != reasonServiceManagedENI {
		t.Fatalf("want 1 service-managed ENI skipped, got %+v", res.Skipped)
	}
	got := string(res.HCL)
	if strings.Contains(got, `"nat"`) {
		t.Errorf("nat_gateway ENI must be dropped\n%s", got)
	}
	if !strings.Contains(got, `"standard"`) {
		t.Errorf("standard ENI must be preserved\n%s", got)
	}
	// The matching import block must be removed from imports.tf (the
	// to-traversal parse + rewrite path), and the standard one preserved.
	importsOut, err := os.ReadFile(filepath.Join(dir, importsFile))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(importsOut), "aws_network_interface.nat") {
		t.Errorf("nat_gateway import block must be removed from imports.tf\n%s", importsOut)
	}
	if !strings.Contains(string(importsOut), "aws_network_interface.standard") {
		t.Errorf("standard import block must be preserved\n%s", importsOut)
	}
}

// TestPruneUnimportable_NoopWhenAllImportable pins the byte-stable round-trip
// the golden tests rely on: when nothing is un-importable the generated bytes
// pass through unchanged and imports.tf is untouched.
func TestPruneUnimportable_NoopWhenAllImportable(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	importsBody := `import {
  to = aws_network_interface.standard
  id = "eni-std@us-east-1"
}
`
	writeImports(t, dir, importsBody)
	generated := []byte(`resource "aws_network_interface" "standard" {
  private_ips = ["10.0.0.5"]
}
`)
	res, err := pruneUnimportable(dir, generated)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 0 {
		t.Fatalf("want 0 skipped, got %+v", res.Skipped)
	}
	if string(res.HCL) != string(generated) {
		t.Errorf("HCL must be byte-stable when nothing is pruned")
	}
	importsOut, err := os.ReadFile(filepath.Join(dir, importsFile))
	if err != nil {
		t.Fatal(err)
	}
	if string(importsOut) != importsBody {
		t.Errorf("imports.tf must be untouched when nothing is pruned")
	}
}

// TestUnimportableReason pins the per-type classification directly.
func TestUnimportableReason(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name   string
		tfType string
		hcl    string
		want   string
	}{
		{"managed kms alias", "aws_kms_alias", `resource "aws_kms_alias" "x" {
  name = "alias/aws/ebs"
}`, reasonAWSManagedKMSAlias},
		{"customer kms alias", "aws_kms_alias", `resource "aws_kms_alias" "x" {
  name = "alias/io-foo"
}`, ""},
		{"nat gateway eni", "aws_network_interface", `resource "aws_network_interface" "x" {
  interface_type = "nat_gateway"
}`, reasonServiceManagedENI},
		{"vpc endpoint eni", "aws_network_interface", `resource "aws_network_interface" "x" {
  interface_type = "vpc_endpoint"
}`, reasonServiceManagedENI},
		{"standard eni interface literal", "aws_network_interface", `resource "aws_network_interface" "x" {
  interface_type = "interface"
}`, ""},
		{"standard eni no interface_type", "aws_network_interface", `resource "aws_network_interface" "x" {
  private_ips = ["10.0.0.5"]
}`, ""},
		{"efa eni settable", "aws_network_interface", `resource "aws_network_interface" "x" {
  interface_type = "efa"
}`, ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			body := parseSingleResourceBody(t, tc.hcl)
			if got := unimportableReason(tc.tfType, body); got != tc.want {
				t.Errorf("unimportableReason(%s) = %q, want %q", tc.tfType, got, tc.want)
			}
		})
	}
}
