package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"

	"github.com/luthersystems/insideout-terraform-presets/pkg/imported"
)

type managedMapEntry struct {
	ManagedKey string
	TFType     string
}

// runManagedMap emits the managed-component -> primary imported tfType map
// as a TypeScript const for downstream TS consumers.
func runManagedMap(args []string) int {
	fs := flag.NewFlagSet("managed-map", flag.ExitOnError)
	out := fs.String("output", "", "path to write TypeScript to (default: stdout)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	buf := emitManagedMapTS(buildManagedMapEntries())
	if *out == "" {
		if _, err := os.Stdout.Write(buf); err != nil {
			fmt.Fprintf(os.Stderr, "write stdout: %v\n", err)
			return 1
		}
		return 0
	}
	if err := os.WriteFile(*out, buf, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		return 1
	}
	return 0
}

func buildManagedMapEntries() []managedMapEntry {
	m := imported.ManagedComponentPrimaryTFTypes()
	entries := make([]managedMapEntry, 0, len(m))
	for key, tfType := range m {
		entries = append(entries, managedMapEntry{
			ManagedKey: string(key),
			TFType:     tfType,
		})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ManagedKey < entries[j].ManagedKey
	})
	return entries
}

func emitManagedMapTS(entries []managedMapEntry) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Generated by `imported-codegen managed-map`; do not edit.\n")
	buf.WriteString("// Source: pkg/imported.ManagedComponentPrimaryTFTypes.\n\n")
	buf.WriteString("export const MANAGED_TO_IMPORTED_TFTYPE = {\n")
	for _, entry := range entries {
		fmt.Fprintf(&buf, "  %s: %q,\n", entry.ManagedKey, entry.TFType)
	}
	buf.WriteString("} as const;\n\n")
	buf.WriteString("export type ManagedComponentKey = keyof typeof MANAGED_TO_IMPORTED_TFTYPE;\n")
	buf.WriteString("export type ImportedPrimaryTfType = (typeof MANAGED_TO_IMPORTED_TFTYPE)[ManagedComponentKey];\n")
	return buf.Bytes()
}
