package main

import (
	"fmt"
	"reflect"
	"slices"
	"strings"
	"unicode"
)

// engine walks a typed/API struct pair via reflection at codegen time
// and emits Go source for a `mapXxx` function plus child-struct
// `enrichXxx` helpers. Pure compile-time reflection — nothing the
// engine emits uses reflect at runtime.
//
// One engine instance generates one file. Two passes:
//  1. emitTopLevel walks the typed struct's fields, dispatching to
//     emitScalarField / emitMapField / emitStringSliceField /
//     emitBlockField / emitWrapperIndirection per field shape.
//  2. As nested-block fields are encountered, ensureHelper appends a
//     helper func to helperBuf for each unique child struct
//     (idempotent — child struct emitted once even if reachable
//     through multiple paths).
type engine struct {
	t target

	mainBuf   strings.Builder // top-level mapXxx function body
	helperBuf strings.Builder // enrichXxx helper functions
	helpers   []string        // names of helpers already emitted (dedupe)
}

func newEngine(t target) *engine {
	return &engine{t: t}
}

func (e *engine) line(format string, args ...any) {
	fmt.Fprintf(&e.mainBuf, format, args...)
	e.mainBuf.WriteByte('\n')
}

// generate produces the full file body — header, imports, preamble,
// top-level mapXxx, and child enrichXxx helpers — and returns it
// before gofmt. Callers (main.go) gofmt and write to disk.
func (e *engine) generate() string {
	e.line("func %s(b *%s.%s, projectID string) *generated.%s {",
		e.t.funcName, e.t.apiPkgAlias, e.t.apiType.Name(), e.t.typedType.Name())
	e.line("\tout := &generated.%s{}", e.t.typedType.Name())
	e.emitFields(e.t.typedType, e.t.apiType, "b", e.t.typedType.Name())
	e.line("\treturn out")
	e.line("}")

	body := e.mainBuf.String() + "\n" + e.helperBuf.String()

	// Only include the strings import if the body actually
	// references it. The labels-map filter and the per-type
	// preamble helpers (pubsub_topic / pubsub_subscription /
	// secret_manager_secret all use strings.LastIndex) account for
	// every current use, but a target like compute_network has no
	// labels field and no strings-using preamble, so the import
	// would dangle and go vet / build would reject the file.
	stringsImport := ""
	if strings.Contains(e.t.preamble, "strings.") || strings.Contains(body, "strings.") {
		stringsImport = "\t\"strings\"\n\n"
	}

	header := fmt.Sprintf(`// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: typed Layer 1 struct generated.%s
//         + raw API struct %s.%s
// Run: go generate ./cmd/insideout-import/gcpdiscover/...
//      (or: go run ./cmd/enrichgen)

package %s

import (
%s	%s %q

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

%s`,
		e.t.typedType.Name(), e.t.apiPkgAlias, e.t.apiType.Name(),
		e.t.outputPkg,
		stringsImport,
		e.t.apiPkgAlias, e.t.apiPkgImport,
		e.t.preamble,
	)

	return header + body
}

// emitFields walks a typed struct's fields and emits assignments to
// out.<F> for each. parentVar is the local variable name holding the
// API struct (e.g. "b"). typedTypeName is the Go name of the typed
// struct, used as the override-key prefix.
func (e *engine) emitFields(typedType, apiType reflect.Type, parentVar, typedTypeName string) {
	for i := 0; i < typedType.NumField(); i++ {
		f := typedType.Field(i)
		tag, isBlock, isBlocks := tfTag(f)
		if tag == "" {
			continue
		}

		key := typedTypeName + "." + tag

		if ov, has := e.t.overrides[key]; has {
			snip := ov.snippet(parentVar, f.Name)
			if snip == "" {
				continue
			}
			e.line("\t%s", snip)
			continue
		}

		if wi, has := e.t.wrapperIndirections[key]; has {
			e.emitWrapperIndirection(f, wi.APIPath, wi.NilGuardChain, parentVar)
			continue
		}

		apiName := snakeToCamel(tag)
		if alias, has := e.t.aliasFields[key]; has {
			apiName = alias
		}
		af, ok := apiField(apiType, apiName)
		if !ok {
			e.line("\t// TODO(enrichgen): %s.%s — no API field %q on %s",
				typedTypeName, tag, apiName, apiType.String())
			continue
		}

		if isBlocks || isBlock {
			e.emitBlockField(f, af, parentVar)
			continue
		}

		switch f.Type.Kind() {
		case reflect.Map:
			e.emitMapField(f, af, parentVar)
		case reflect.Slice:
			if f.Type.Elem().Kind() == reflect.Pointer {
				// []*Value[string] — string list.
				e.emitStringSliceField(f, af, parentVar)
			} else {
				// []Block — should have been caught by isBlock/isBlocks
				// above; if we reach here the typed schema marked it
				// non-block which is a bug worth surfacing.
				e.line("\t// TODO(enrichgen): %s — slice of struct without `,blocks` tag",
					f.Name)
			}
		default:
			e.emitScalarField(f, af, parentVar)
		}
	}
}

// emitScalarField handles *Value[T] where T is bool / string / int64 / float64.
func (e *engine) emitScalarField(f, af reflect.StructField, parentVar string) {
	t := valueTypeParam(f.Type)
	if t == nil {
		e.line("\t// TODO(enrichgen): %s — typed field is not *Value[T]; got %s",
			f.Name, f.Type.String())
		return
	}

	apiAccess := parentVar + "." + af.Name
	apiKind := af.Type.Kind()

	deref := apiAccess
	guard := ""
	if apiKind == reflect.Pointer {
		guard = apiAccess + " != nil"
		deref = "*" + apiAccess
		apiKind = af.Type.Elem().Kind()
	}

	cast := deref
	switch t.Kind() {
	case reflect.Float64:
		if apiKind == reflect.Int64 || apiKind == reflect.Int {
			cast = "float64(" + deref + ")"
		}
	case reflect.Int64:
		if apiKind == reflect.Int {
			cast = "int64(" + deref + ")"
		}
	}

	switch t.Kind() {
	case reflect.String:
		if guard == "" {
			guard = apiAccess + " != \"\""
		}
		e.emitGuardedAssign(f.Name, cast, guard)
	case reflect.Bool:
		// Bool fields with no special override: emit unconditionally
		// when there's no pointer guard. The hand-written reference
		// emits force_destroy / event-based-hold / requester_pays /
		// enable_object_retention as default-false; bool fields inside
		// nested blocks (e.g. versioning.enabled) emit the API value
		// directly without a non-zero guard. Pointer-to-bool API
		// fields are guarded on non-nil.
		if guard != "" {
			e.emitGuardedAssign(f.Name, cast, guard)
		} else {
			e.line("\tout.%s = generated.LiteralOf(%s)", f.Name, cast)
		}
	case reflect.Int64:
		if guard == "" {
			guard = apiAccess + " != 0"
		}
		e.emitGuardedAssign(f.Name, cast, guard)
	case reflect.Float64:
		if guard == "" {
			guard = apiAccess + " != 0"
		}
		e.emitGuardedAssign(f.Name, cast, guard)
	default:
		e.line("\t// TODO(enrichgen): %s — unhandled scalar T=%s", f.Name, t.String())
	}
}

func (e *engine) emitGuardedAssign(field, cast, guard string) {
	e.line("\tif %s {", guard)
	e.line("\t\tout.%s = generated.LiteralOf(%s)", field, cast)
	e.line("\t}")
}

func (e *engine) emitMapField(f, af reflect.StructField, parentVar string) {
	// labels is the only map field today and has a goog-* filter
	// requirement. Other map-typed fields would follow the simple
	// branch below; if/when one shows up that needs filtering, gate it
	// via an override snippet keyed on the typed-struct.field name
	// instead of hardcoding by Go field name here.
	if f.Name == "Labels" {
		e.line(`	if len(%s.Labels) > 0 {
		labels := map[string]*generated.Value[string]{}
		for k, v := range %s.Labels {
			if strings.HasPrefix(k, "goog-") || strings.HasPrefix(k, "goog_") {
				continue
			}
			labels[k] = generated.LiteralOf(v)
		}
		if len(labels) > 0 {
			out.%s = labels
		}
	}`, parentVar, parentVar, f.Name)
		e.mainBuf.WriteByte('\n')
		return
	}
	e.line(`	if len(%s.%s) > 0 {
		m := map[string]*generated.Value[string]{}
		for k, v := range %s.%s {
			m[k] = generated.LiteralOf(v)
		}
		out.%s = m
	}`, parentVar, af.Name, parentVar, af.Name, f.Name)
	e.mainBuf.WriteByte('\n')
}

func (e *engine) emitStringSliceField(f, af reflect.StructField, parentVar string) {
	e.line(`	if len(%s.%s) > 0 {
		out.%s = stringSliceToValues(%s.%s)
	}`, parentVar, af.Name, f.Name, parentVar, af.Name)
	e.mainBuf.WriteByte('\n')
}

// emitBlockField handles a nested block. Two shapes on the typed side:
//   - typed: []ChildBlock paired with API: *APIChildStruct (singleton)
//   - typed: []ChildBlock paired with API: []*APIChildStruct (slice)
//
// A third shape — typed: *ChildBlock — is also supported for
// completeness though the Layer 1 codegen always emits []ChildBlock.
func (e *engine) emitBlockField(f, af reflect.StructField, parentVar string) {
	var childTyped reflect.Type
	switch f.Type.Kind() {
	case reflect.Slice, reflect.Pointer:
		childTyped = f.Type.Elem()
	default:
		e.line("\t// TODO(enrichgen): %s — unsupported typed block kind %s",
			f.Name, f.Type.Kind())
		return
	}

	var childAPI reflect.Type
	apiSliceShape := false
	switch af.Type.Kind() {
	case reflect.Pointer:
		childAPI = af.Type.Elem()
	case reflect.Slice:
		apiSliceShape = true
		elem := af.Type.Elem()
		if elem.Kind() == reflect.Pointer {
			childAPI = elem.Elem()
		} else {
			childAPI = elem
		}
	default:
		e.line("\t// TODO(enrichgen): %s — unsupported API block kind %s",
			f.Name, af.Type.Kind())
		return
	}

	helperName := e.t.helperPrefix + childTyped.Name()
	e.ensureHelper(helperName, childTyped, childAPI)

	apiAccess := parentVar + "." + af.Name

	gate := apiAccess + " != nil"
	if apiSliceShape {
		gate = "len(" + apiAccess + ") > 0"
	}
	if g, has := e.t.blockGates[f.Name]; has {
		gate = g(apiAccess)
	}

	if apiSliceShape {
		e.line(`	if %s {
		blocks := make([]generated.%s, 0, len(%s))
		for _, x := range %s {
			if x == nil {
				continue
			}
			blocks = append(blocks, %s(x))
		}
		if len(blocks) > 0 {
			out.%s = blocks
		}
	}`, gate, childTyped.Name(), apiAccess, apiAccess, helperName, f.Name)
		e.mainBuf.WriteByte('\n')
		return
	}

	if f.Type.Kind() == reflect.Slice {
		e.line(`	if %s {
		out.%s = []generated.%s{%s(%s)}
	}`, gate, f.Name, childTyped.Name(), helperName, apiAccess)
	} else {
		e.line(`	if %s {
		v := %s(%s)
		out.%s = &v
	}`, gate, helperName, apiAccess, f.Name)
	}
	e.mainBuf.WriteByte('\n')
}

// emitWrapperIndirection handles the lifecycle_rule shape — typed is
// slice-of-block, API is wrapper-then-slice (Lifecycle.Rule).
func (e *engine) emitWrapperIndirection(f reflect.StructField, apiPath, nilGuardFmt, parentVar string) {
	if f.Type.Kind() != reflect.Slice {
		e.line("\t// TODO(enrichgen): %s — wrapper indirection only supports slice-of-block typed shape",
			f.Name)
		return
	}
	childTyped := f.Type.Elem()
	apiAccess := parentVar + "." + apiPath
	guard := fmt.Sprintf(nilGuardFmt, parentVar) + " && len(" + apiAccess + ") > 0"

	// Resolve API child type by walking apiPath on the API root.
	t := e.t.apiType
	for p := range strings.SplitSeq(apiPath, ".") {
		ff, ok := t.FieldByName(p)
		if !ok {
			e.line("\t// TODO(enrichgen): %s — wrapper path %q broken at %q",
				f.Name, apiPath, p)
			return
		}
		t = ff.Type
		if t.Kind() == reflect.Pointer {
			t = t.Elem()
		}
	}
	if t.Kind() != reflect.Slice {
		e.line("\t// TODO(enrichgen): %s — wrapper terminal not a slice (%s)",
			f.Name, t.String())
		return
	}
	elem := t.Elem()
	if elem.Kind() == reflect.Pointer {
		elem = elem.Elem()
	}
	apiChild := elem

	helperName := e.t.helperPrefix + childTyped.Name()
	e.ensureHelper(helperName, childTyped, apiChild)

	e.line(`	if %s {
		blocks := make([]generated.%s, 0, len(%s))
		for _, r := range %s {
			if r == nil {
				continue
			}
			blocks = append(blocks, %s(r))
		}
		if len(blocks) > 0 {
			out.%s = blocks
		}
	}`, guard, childTyped.Name(), apiAccess, apiAccess, helperName, f.Name)
	e.mainBuf.WriteByte('\n')
}

// ensureHelper emits a helper function for one child typed struct,
// idempotently. The helper shape is:
//
//	func enrichXxx(b *apiPkg.YyyType) generated.XxxType {
//	    out := generated.XxxType{}
//	    // emitFields(...)
//	    return out
//	}
//
// Helpers are appended to helperBuf so they emit after the top-level
// mapXxx; this keeps the file readable top-down.
func (e *engine) ensureHelper(name string, typedType, apiType reflect.Type) {
	if slices.Contains(e.helpers, name) {
		return
	}
	e.helpers = append(e.helpers, name)

	// Redirect mainBuf temporarily so recursive emitFields calls land
	// in the right place. Save / restore mainBuf around the helper
	// emission, then concatenate into helperBuf.
	saved := e.mainBuf
	e.mainBuf = strings.Builder{}

	e.line("func %s(b *%s.%s) generated.%s {",
		name, e.t.apiPkgAlias, apiType.Name(), typedType.Name())
	e.line("\tout := generated.%s{}", typedType.Name())
	e.emitFields(typedType, apiType, "b", typedType.Name())
	e.line("\treturn out")
	e.line("}")
	e.line("")

	e.helperBuf.WriteString(e.mainBuf.String())
	e.mainBuf = saved
}

// tfTag extracts the snake-case tag from a `tf:"..."` struct tag and
// flags `,block` / `,blocks` suffixes used by the Layer 1 codegen.
func tfTag(f reflect.StructField) (tag string, isBlock, isBlocks bool) {
	raw := f.Tag.Get("tf")
	if raw == "" {
		return "", false, false
	}
	bits := strings.Split(raw, ",")
	tag = bits[0]
	for _, b := range bits[1:] {
		switch b {
		case "block":
			isBlock = true
		case "blocks":
			isBlocks = true
		}
	}
	return
}

// snakeToCamel converts a snake_case TF tag to the matching CamelCase
// field name on the raw API struct. Google's API code-generated
// structs use first-letter-uppercase per word and treat initialisms
// as ordinary words (Kms not KMS, Id not ID).
func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	var out strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		out.WriteString(string(r))
	}
	return out.String()
}

// apiField finds the named field on the API struct, with a small
// initialism-swap fallback. The Google API generator uses Kms / Id /
// Url / Ip / Http title-case while a naive snakeToCamel converts
// `kms_key_name` to `KmsKeyName` correctly — but `id` gets converted
// to `Id`, which already matches. The swap table covers the rare cases
// where the typed-side TF tag uses an initialism the API generator
// expanded back to title-case.
func apiField(apiType reflect.Type, camelName string) (reflect.StructField, bool) {
	if f, ok := apiType.FieldByName(camelName); ok {
		return f, true
	}
	alt := camelName
	for _, swap := range []struct{ from, to string }{
		{"ID", "Id"}, {"URL", "Url"}, {"KMS", "Kms"}, {"IP", "Ip"}, {"HTTP", "Http"},
	} {
		alt = strings.ReplaceAll(alt, swap.from, swap.to)
	}
	if alt != camelName {
		if f, ok := apiType.FieldByName(alt); ok {
			return f, true
		}
	}
	return reflect.StructField{}, false
}

// valueTypeParam returns the T in *Value[T] / Value[T], or nil if the
// field type isn't a Value generic. The Layer 1 codegen wraps every
// scalar field in *Value[T]; the engine reads T to pick the right
// LiteralOf cast.
func valueTypeParam(t reflect.Type) reflect.Type {
	if t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return nil
	}
	if !strings.HasPrefix(t.Name(), "Value[") {
		return nil
	}
	for i := 0; i < t.NumField(); i++ {
		ff := t.Field(i)
		if ff.Name == "Literal" && ff.Type.Kind() == reflect.Pointer {
			return ff.Type.Elem()
		}
	}
	return nil
}
