package main

import (
	"fmt"
	"sort"
	"strings"
)

// fetcherEngine emits the optional list / describe helper functions
// declared in target.fetchers into a single .gen.go file. Each entry
// becomes one helper that:
//
//   - builds the SDK input struct from inputAssign,
//   - invokes either a single sdkMethod call or a paginator loop,
//   - nil-checks the response, and
//   - returns either the resultExpr (non-paginated) or the accumulated
//     []accumulatorElemType (paginated).
//
// The engine is independent of the struct-mapping engine — they share
// nothing but the package they emit into. One fetcherEngine instance
// generates one file; main.go iterates over targets and invokes both
// engines as needed.
type fetcherEngine struct {
	t target

	buf strings.Builder
}

// newFetcherEngine constructs an engine pinned to a single target.
// Caller is responsible for verifying target.fetchers is non-empty
// before invoking.
func newFetcherEngine(t target) *fetcherEngine {
	return &fetcherEngine{t: t}
}

func (e *fetcherEngine) line(format string, args ...any) {
	fmt.Fprintf(&e.buf, format, args...)
	e.buf.WriteByte('\n')
}

// generate emits the full file body (header + imports + helper
// functions) and returns the pre-gofmt source. Caller (main.go) gofmts
// and writes to disk.
func (e *fetcherEngine) generate() string {
	// Sort fetchers by funcName for deterministic output independent
	// of declaration order in the per-type registration file.
	fetchers := append([]fetcherTarget(nil), e.t.fetchers...)
	sort.Slice(fetchers, func(i, j int) bool {
		return fetchers[i].funcName < fetchers[j].funcName
	})

	for _, f := range fetchers {
		e.emitFetcher(f)
	}
	body := e.buf.String()

	// Discover the cloud directory (aws / gcp / ...) from the output
	// path so the `go generate` hint in the header matches the
	// existing engine.go convention.
	cloud := cloudFromOutputPath(e.t.fetchersOutputPath)

	// Detect which optional imports the body actually references.
	// We only emit each import line when the body mentions it, to
	// keep the gofmt output clean and to avoid unused-import build
	// failures.
	imports := collectFetcherImports(fetchers, body, e.t.apiPkgAlias, e.t.apiPkgImport)

	header := fmt.Sprintf(`// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: fetcher helpers for %s
// Run: go generate ./cmd/insideout-import/%sdiscover/...
//      (or: go run ./cmd/enrichgen)

package %s

import (
%s)

`,
		e.t.typedType.Name(),
		cloud,
		e.t.outputPkg,
		imports,
	)

	return header + body
}

// emitFetcher writes one helper function. Paginated and non-paginated
// shapes diverge after the input-struct construction; both share the
// signature, doc comment, and input setup.
func (e *fetcherEngine) emitFetcher(f fetcherTarget) {
	if f.doc != "" {
		for ln := range strings.SplitSeq(f.doc, "\n") {
			if ln == "" {
				e.line("//")
				continue
			}
			e.line("// %s", ln)
		}
	}

	sig := fmt.Sprintf("func %s(ctx context.Context, c %s", f.funcName, f.clientType)
	if strings.TrimSpace(f.paramArg) != "" {
		sig += ", " + f.paramArg
	}
	if f.paginator != "" {
		sig += fmt.Sprintf(") ([]%s, error) {", f.accumulatorElemType)
	} else {
		sig += fmt.Sprintf(") (%s, error) {", f.resultType)
	}
	e.line("%s", sig)

	// Build the input struct. Keys sorted for deterministic emission.
	e.line("\tinput := &%s.%s{", f.sdkClientPkgAlias, f.inputType)
	keys := make([]string, 0, len(f.inputAssign))
	for k := range f.inputAssign {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.line("\t\t%s: %s,", k, f.inputAssign[k])
	}
	e.line("\t}")

	if f.paginator != "" {
		e.emitPaginated(f)
	} else {
		e.emitSingleCall(f)
	}

	e.line("}")
	e.line("")
}

// emitSingleCall writes the non-paginated body: invoke sdkMethod, nil-
// check the response, return resultExpr.
func (e *fetcherEngine) emitSingleCall(f fetcherTarget) {
	zero := zeroValueForResult(f.resultType)
	e.line("\tout, err := c.%s(ctx, input)", f.sdkMethod)
	e.line("\tif err != nil {")
	if zero.todo {
		e.line("\t\t// TODO(enrichgen): unsupported result shape %q — caller must handle.", f.resultType)
		e.line("\t\treturn %s, err", zero.expr)
	} else {
		e.line("\t\treturn %s, err", zero.expr)
	}
	e.line("\t}")
	e.line("\tif out == nil {")
	e.line("\t\treturn %s, nil", zero.expr)
	e.line("\t}")
	e.line("\treturn %s, nil", f.resultExpr)
}

// emitPaginated writes the paginator-loop body: construct paginator,
// loop while HasMorePages, append accumulator field across pages.
func (e *fetcherEngine) emitPaginated(f fetcherTarget) {
	e.line("\tp := %s.%s(c, input)", f.sdkClientPkgAlias, f.paginator)
	e.line("\tvar out []%s", f.accumulatorElemType)
	e.line("\tfor p.HasMorePages() {")
	e.line("\t\tpage, err := p.NextPage(ctx)")
	e.line("\t\tif err != nil {")
	e.line("\t\t\treturn nil, err")
	e.line("\t\t}")
	e.line("\t\tif page == nil {")
	e.line("\t\t\tcontinue")
	e.line("\t\t}")
	e.line("\t\tout = append(out, page.%s...)", f.accumulatorField)
	e.line("\t}")
	e.line("\treturn out, nil")
}

// resultZero captures how to spell the zero value for a fetcher's
// declared resultType, used in error-path returns. Slice / pointer
// types are spelled as the literal "nil"; anything else is flagged as
// a TODO so the engine emits a build-time signal rather than a silent
// wrong default.
type resultZero struct {
	expr string
	todo bool
}

func zeroValueForResult(resultType string) resultZero {
	t := strings.TrimSpace(resultType)
	switch {
	case strings.HasPrefix(t, "[]"), strings.HasPrefix(t, "*"):
		return resultZero{expr: "nil"}
	default:
		// Scalar shape — emit a TODO so future contributors notice the
		// gap. All current fetcher entries return slices or pointers,
		// so this branch only exists to surface the omission if a
		// scalar return shows up.
		return resultZero{expr: "nil", todo: true}
	}
}

// cloudFromOutputPath returns the cloud directory ("aws" / "gcp" / ...)
// from a fetcher output path like
// "cmd/insideout-import/awsdiscover/foo_fetchers.gen.go". Used only to
// shape the `go generate` line in the file header; returns "" if the
// path doesn't match the expected pattern so the header degrades
// gracefully rather than emitting a bogus hint.
func cloudFromOutputPath(p string) string {
	const prefix = "cmd/insideout-import/"
	if !strings.HasPrefix(p, prefix) {
		return ""
	}
	rest := strings.TrimPrefix(p, prefix)
	dir, _, ok := strings.Cut(rest, "/")
	if !ok {
		return ""
	}
	if !strings.HasSuffix(dir, "discover") {
		return ""
	}
	return strings.TrimSuffix(dir, "discover")
}

// collectFetcherImports renders the import block contents (one import
// per line, with leading tab) for a fetcher file. Imports emitted:
//
//   - "context" — always (every helper takes ctx context.Context).
//   - "github.com/aws/aws-sdk-go-v2/aws" — only if any inputAssign
//     value mentions "aws." (e.g. aws.String).
//   - the SDK client package(s) — one per unique alias/import pair
//     across all fetchers.
//   - the apiPkg — only if the body references the apiPkgAlias.
func collectFetcherImports(fetchers []fetcherTarget, body, apiAlias, apiImport string) string {
	type imp struct {
		alias string // empty = no alias
		path  string
	}
	var imps []imp
	seen := map[string]bool{}

	add := func(alias, path string) {
		key := alias + "\x00" + path
		if seen[key] {
			return
		}
		seen[key] = true
		imps = append(imps, imp{alias: alias, path: path})
	}

	add("", "context")

	// aws.String / aws.Int32 / etc. show up in inputAssign expressions.
	awsRef := false
	for _, f := range fetchers {
		for _, v := range f.inputAssign {
			if strings.Contains(v, "aws.") {
				awsRef = true
				break
			}
		}
		if awsRef {
			break
		}
	}
	if awsRef {
		add("", "github.com/aws/aws-sdk-go-v2/aws")
	}

	for _, f := range fetchers {
		if f.sdkClientPkgImport == "" || f.sdkClientPkgAlias == "" {
			continue
		}
		add(f.sdkClientPkgAlias, f.sdkClientPkgImport)
	}

	if apiAlias != "" && strings.Contains(body, apiAlias+".") {
		add(apiAlias, apiImport)
	}

	// Sort: stdlib first ("context"), then third-party.
	sort.SliceStable(imps, func(i, j int) bool {
		ai := isStdLib(imps[i].path)
		aj := isStdLib(imps[j].path)
		if ai != aj {
			return ai
		}
		return imps[i].path < imps[j].path
	})

	var b strings.Builder
	prevStd := false
	for i, im := range imps {
		std := isStdLib(im.path)
		if i > 0 && prevStd && !std {
			b.WriteByte('\n')
		}
		if im.alias != "" {
			fmt.Fprintf(&b, "\t%s %q\n", im.alias, im.path)
		} else {
			fmt.Fprintf(&b, "\t%q\n", im.path)
		}
		prevStd = std
	}
	return b.String()
}

// isStdLib reports whether an import path is a standard-library
// package (no dot before the first slash). Good enough for grouping
// imports into the conventional stdlib / third-party blocks.
func isStdLib(p string) bool {
	if before, _, ok := strings.Cut(p, "/"); ok {
		return !strings.Contains(before, ".")
	}
	return !strings.Contains(p, ".")
}
