package main

import (
	"go/format"
	"reflect"
	"testing"

	dynamotypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/luthersystems/insideout-terraform-presets/pkg/composer/imported/generated"
)

// TestFetcherEngineGoldenDynamoDBTableTags pins the gofmt'd emit shape
// for the canonical non-paginated fetcher entry (DynamoDB
// ListTagsOfResource). Pure parity guard — any change to the fetcher
// engine that alters the emitted bytes must update the expected
// constant below in the same patch. Future paginator-shape coverage
// belongs in a sibling test rather than this one.
func TestFetcherEngineGoldenDynamoDBTableTags(t *testing.T) {
	tgt := target{
		typedType:    reflect.TypeFor[generated.AWSDynamodbTable](),
		apiType:      reflect.TypeFor[dynamotypes.TableDescription](),
		outputPkg:    "awsdiscover",
		apiPkgAlias:  "dynamotypes",
		apiPkgImport: "github.com/aws/aws-sdk-go-v2/service/dynamodb/types",
		fetchers: []fetcherTarget{
			{
				funcName: "defaultDynamoDBTableFetchTags",
				doc: `defaultDynamoDBTableFetchTags is the production tags fetch path.
Returns the raw tag slice; the caller flattens it into the typed map.
Pagination is not handled today — DynamoDB's tag-set is capped at 50 per
table by the service, well below the per-page limit, so a single call
covers every realistic case.`,
				clientType:         "*dynamodb.Client",
				paramArg:           "tableArn string",
				sdkMethod:          "ListTagsOfResource",
				inputType:          "ListTagsOfResourceInput",
				inputAssign:        map[string]string{"ResourceArn": "aws.String(tableArn)"},
				resultType:         "[]dynamotypes.Tag",
				resultExpr:         "out.Tags",
				sdkClientPkgImport: "github.com/aws/aws-sdk-go-v2/service/dynamodb",
				sdkClientPkgAlias:  "dynamodb",
			},
		},
		fetchersOutputPath: "cmd/insideout-import/awsdiscover/dynamodb_table_fetchers.gen.go",
	}

	body := newFetcherEngine(tgt).generate()
	formatted, err := format.Source([]byte(body))
	if err != nil {
		t.Fatalf("gofmt failed: %v\n--- raw output ---\n%s", err, body)
	}

	const expected = `// Code generated by cmd/enrichgen — DO NOT EDIT.
//
// Source: fetcher helpers for AWSDynamodbTable
// Run: go generate ./cmd/insideout-import/awsdiscover/...
//      (or: go run ./cmd/enrichgen)

package awsdiscover

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	dynamotypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// defaultDynamoDBTableFetchTags is the production tags fetch path.
// Returns the raw tag slice; the caller flattens it into the typed map.
// Pagination is not handled today — DynamoDB's tag-set is capped at 50 per
// table by the service, well below the per-page limit, so a single call
// covers every realistic case.
func defaultDynamoDBTableFetchTags(ctx context.Context, c *dynamodb.Client, tableArn string) ([]dynamotypes.Tag, error) {
	input := &dynamodb.ListTagsOfResourceInput{
		ResourceArn: aws.String(tableArn),
	}
	out, err := c.ListTagsOfResource(ctx, input)
	if err != nil {
		return nil, err
	}
	if out == nil {
		return nil, nil
	}
	return out.Tags, nil
}
`

	if string(formatted) != expected {
		t.Fatalf("golden mismatch.\n--- want (%d bytes) ---\n%s\n--- got (%d bytes) ---\n%s",
			len(expected), expected, len(formatted), formatted)
	}
}

// TestFetcherEnginePaginatedShape exercises the paginator-loop emit
// branch with an in-memory target that mirrors the AWS Cloud Control
// ListResources shape. The paginator code path is not yet exercised by
// any real fetcher entry — this test pins the emitted shape so the
// branch keeps compiling and stays gofmt-clean as the engine evolves.
func TestFetcherEnginePaginatedShape(t *testing.T) {
	tgt := target{
		typedType:    reflect.TypeFor[generated.AWSDynamodbTable](),
		apiType:      reflect.TypeFor[dynamotypes.TableDescription](),
		outputPkg:    "awsdiscover",
		apiPkgAlias:  "dynamotypes",
		apiPkgImport: "github.com/aws/aws-sdk-go-v2/service/dynamodb/types",
		fetchers: []fetcherTarget{
			{
				funcName:            "examplePaginatedList",
				clientType:          "*cc.Client",
				paramArg:            "typeName string",
				inputType:           "ListResourcesInput",
				inputAssign:         map[string]string{"TypeName": "aws.String(typeName)"},
				sdkClientPkgImport:  "github.com/aws/aws-sdk-go-v2/service/cloudcontrol",
				sdkClientPkgAlias:   "cc",
				paginator:           "NewListResourcesPaginator",
				accumulatorField:    "ResourceDescriptions",
				accumulatorElemType: "cctypes.ResourceDescription",
			},
		},
		fetchersOutputPath: "cmd/insideout-import/awsdiscover/example_fetchers.gen.go",
	}

	body := newFetcherEngine(tgt).generate()
	if _, err := format.Source([]byte(body)); err != nil {
		t.Fatalf("gofmt failed on paginated shape: %v\n--- raw output ---\n%s", err, body)
	}

	// Smoke check: the body must contain the paginator loop scaffolding.
	for _, want := range []string{
		"NewListResourcesPaginator(c, input)",
		"for p.HasMorePages()",
		"p.NextPage(ctx)",
		"append(out, page.ResourceDescriptions...)",
		"[]cctypes.ResourceDescription",
	} {
		if !contains(body, want) {
			t.Errorf("paginated emit missing %q\n--- body ---\n%s", want, body)
		}
	}
}

func contains(s, sub string) bool {
	return len(s) >= len(sub) && indexOf(s, sub) >= 0
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
