package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// adoptExitFatal / adoptExitDrift are the documented exit codes for the
// adopt subcommand. README.md is the source of truth — keep in sync.
const (
	adoptExitOK    = 0
	adoptExitFatal = 1
	adoptExitDrift = 2

	importsFile = "imports.tf"
	planTimeout = 10 * time.Minute
)

// adoptHeader is prepended to imports.tf so a future re-run knows the file
// was machine-generated. Comment style matches the rest of the repo.
const adoptHeader = `# Generated by insideout-import adopt — do not hand-edit.
# Each block adopts an existing cloud resource into the matching Terraform
# address in this stack. Re-running the adopt command regenerates this file.

`

func runAdopt(args []string) int {
	fs := flag.NewFlagSet("adopt", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, `insideout-import adopt — emit import blocks for a known preset stack.

Usage:
  insideout-import adopt --stack-dir DIR (--import 'ADDR=ID' ...| --imports-file FILE) [flags]

Flags:`)
		fs.PrintDefaults()
		fmt.Fprintln(os.Stderr, `
Exit codes:
  0  imports.tf written and (when verified) terraform plan is import-only
  2  imports.tf written but terraform plan showed unrelated changes
  1  fatal: bad inputs, terraform errors, or plan parse failure`)
	}

	stackDir := fs.String("stack-dir", "", "path to the composed preset stack (required)")
	importsFilePath := fs.String("imports-file", "", "path to a JSON file of [{\"address\":..., \"import_id\":...}] entries")
	noPlan := fs.Bool("no-plan", false, "skip the terraform plan verification step")
	tfBinary := fs.String("terraform-binary", "", "path to the terraform binary (default: lookup PATH)")

	var importFlags multiString
	fs.Var(&importFlags, "import", "import pair as ADDRESS=IMPORT_ID (repeatable)")

	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return adoptExitOK
		}
		return adoptExitFatal
	}

	if strings.TrimSpace(*stackDir) == "" {
		fmt.Fprintln(os.Stderr, "adopt: --stack-dir is required")
		fs.Usage()
		return adoptExitFatal
	}
	info, err := os.Stat(*stackDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "adopt: --stack-dir %q: %v\n", *stackDir, err)
		return adoptExitFatal
	}
	if !info.IsDir() {
		fmt.Fprintf(os.Stderr, "adopt: --stack-dir %q is not a directory\n", *stackDir)
		return adoptExitFatal
	}

	pairs, err := collectPairs(importFlags, *importsFilePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "adopt: %v\n", err)
		return adoptExitFatal
	}
	if len(pairs) == 0 {
		fmt.Fprintln(os.Stderr, "adopt: no imports specified (use --import or --imports-file)")
		return adoptExitFatal
	}

	out := renderImportsFile(pairs)
	outPath := filepath.Join(*stackDir, importsFile)
	if err := os.WriteFile(outPath, out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "adopt: write %s: %v\n", outPath, err)
		return adoptExitFatal
	}
	fmt.Printf("wrote %s (%d import blocks)\n", outPath, len(pairs))

	if *noPlan {
		return adoptExitOK
	}

	tfBin := *tfBinary
	if tfBin == "" {
		path, err := exec.LookPath("terraform")
		if err != nil {
			fmt.Fprintln(os.Stderr, "adopt: terraform not found on PATH; pass --terraform-binary or use --no-plan")
			return adoptExitFatal
		}
		tfBin = path
	}

	ctx, cancel := context.WithTimeout(context.Background(), planTimeout)
	defer cancel()

	addrs := make(map[string]struct{}, len(pairs))
	for _, p := range pairs {
		addrs[p.Address] = struct{}{}
	}
	verdict, err := verifyPlan(ctx, tfBin, *stackDir, addrs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "adopt: plan verification failed: %v\n", err)
		return adoptExitFatal
	}
	if verdict.unrelated() > 0 {
		fmt.Fprintf(os.Stderr, "adopt: plan shows %d unrelated change(s) beyond the imports — operator must reconcile\n", verdict.unrelated())
		for _, line := range verdict.unrelatedSummary {
			fmt.Fprintln(os.Stderr, "  "+line)
		}
		return adoptExitDrift
	}
	fmt.Printf("plan is import-only (%d resource(s) imported)\n", verdict.imports)
	return adoptExitOK
}

// collectPairs merges --import flags and --imports-file content into a
// deterministic list, deduplicating by address. Later entries win on
// duplicate addresses but a warning is printed so operators notice.
func collectPairs(flagPairs []string, filePath string) ([]importPair, error) {
	bag := make(map[string]importPair)
	order := []string{}

	add := func(p importPair, src string) {
		if _, dup := bag[p.Address]; dup {
			fmt.Fprintf(os.Stderr, "adopt: warning: duplicate address %q in %s — keeping later value\n", p.Address, src)
		} else {
			order = append(order, p.Address)
		}
		bag[p.Address] = p
	}

	for _, raw := range flagPairs {
		p, err := parseImportFlag(raw)
		if err != nil {
			return nil, fmt.Errorf("--import: %w", err)
		}
		add(p, "--import flags")
	}

	if filePath != "" {
		filePairs, err := readImportsFile(filePath)
		if err != nil {
			return nil, fmt.Errorf("--imports-file %s: %w", filePath, err)
		}
		for _, p := range filePairs {
			add(p, "--imports-file")
		}
	}

	out := make([]importPair, 0, len(order))
	for _, addr := range order {
		out = append(out, bag[addr])
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Address < out[j].Address })
	return out, nil
}

// importsFileEntry is the JSON wire format for --imports-file. Snake_case
// field names match the rest of the project's machine-readable surfaces
// (imported.json, ResourceIdentity).
type importsFileEntry struct {
	Address  string `json:"address"`
	ImportID string `json:"import_id"`
}

func readImportsFile(path string) ([]importPair, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var entries []importsFileEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return nil, fmt.Errorf("parse JSON: %w", err)
	}
	out := make([]importPair, 0, len(entries))
	for i, e := range entries {
		if strings.TrimSpace(e.Address) == "" {
			return nil, fmt.Errorf("entry %d: empty address", i)
		}
		if strings.TrimSpace(e.ImportID) == "" {
			return nil, fmt.Errorf("entry %d: empty import_id", i)
		}
		if err := validateAddress(e.Address); err != nil {
			return nil, fmt.Errorf("entry %d: invalid address %q: %w", i, e.Address, err)
		}
		out = append(out, importPair{Address: e.Address, ImportID: e.ImportID})
	}
	return out, nil
}

// renderImportsFile emits the contents of imports.tf for the given pairs.
// Pairs are written in lexicographic address order so re-runs against the
// same input produce byte-identical files (golden-test friendly).
func renderImportsFile(pairs []importPair) []byte {
	sorted := make([]importPair, len(pairs))
	copy(sorted, pairs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Address < sorted[j].Address })

	var b strings.Builder
	b.WriteString(adoptHeader)
	for i, p := range sorted {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "import {\n  to = %s\n  id = %q\n}\n", p.Address, p.ImportID)
	}
	return []byte(b.String())
}

// multiString is a flag.Value that accumulates repeated string flags.
type multiString []string

func (m *multiString) String() string     { return strings.Join(*m, ",") }
func (m *multiString) Set(v string) error { *m = append(*m, v); return nil }
